import * as React from 'react';
import {
  FONT_SANS,
  FONT_MONO,
  CORNER_SIZE,
  EDGE_SIZE,
  EDGE_CURSORS,
  COLOR_RED,
  COLOR_GREEN,
  COLOR_INK,
  COLOR_MUTED,
  COLOR_SURFACE,
  COLOR_BORDER,
  COLOR_BG_SUBTLE,
  type Edge,
} from './constants';

// ---------------------------------------------------------------------------
// Styles — inline to avoid CSS dependency, consistent with the rest of the
// dev tooling which must render before theme CSS loads.
// ---------------------------------------------------------------------------

export const panelStyles = {
  container: {
    position: 'fixed',
    background: COLOR_BG_SUBTLE,
    borderRadius: 12,
    boxShadow: '0 8px 32px rgba(0,0,0,0.18), 0 2px 8px rgba(0,0,0,0.08)',
    border: `1px solid ${COLOR_BORDER}`,
    display: 'flex',
    flexDirection: 'column',
    fontFamily: FONT_SANS,
    color: COLOR_INK,
    zIndex: 2147483644,
    WebkitFontSmoothing: 'antialiased',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 16px 10px',
    background: COLOR_SURFACE,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: COLOR_INK,
    margin: 0,
  },
  srOnly: {
    position: 'absolute',
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: 'hidden',
    clip: 'rect(0,0,0,0)',
    whiteSpace: 'nowrap',
    border: 0,
  },
  closeButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    color: COLOR_MUTED,
    padding: '4px 6px',
    borderRadius: 4,
    lineHeight: 1,
    fontFamily: FONT_SANS,
  },
  resetButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: COLOR_MUTED,
    padding: '4px 6px',
    borderRadius: 4,
    lineHeight: 1,
    fontFamily: FONT_SANS,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resolvedBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 16px',
    background: '#f0fdf4',
    color: COLOR_GREEN,
    fontSize: 13,
    fontWeight: 500,
    borderBottom: `1px solid #bbf7d0`,
  },
  resolvedIcon: {
    fontSize: 14,
    fontWeight: 700,
  },

  // ── Tab bar ──────────────────────────────────────────────────
  tabBar: {
    display: 'flex',
    gap: 0,
    background: COLOR_SURFACE,
    borderBottom: `1px solid ${COLOR_BORDER}`,
    padding: '0 16px',
  },
  tab: {
    flex: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: '10px 12px',
    fontSize: 13,
    fontWeight: 600,
    color: COLOR_MUTED,
    background: 'none',
    border: 'none',
    borderBottomWidth: 2,
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    cursor: 'pointer',
    fontFamily: FONT_SANS,
    transition: 'color 0.15s, border-color 0.15s',
  },
  tabActive: {
    color: COLOR_INK,
    borderBottomColor: COLOR_INK,
  },
  tabCount: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 20,
    height: 20,
    padding: '0 6px',
    borderRadius: 10,
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1,
  },

  // ── Card list ────────────────────────────────────────────────
  // flex: 1 lets the list fill available space. The user controls panel
  // size via drag-to-resize, so the list grows/shrinks accordingly.
  list: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto',
    padding: '8px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  emptyTabState: {
    padding: '24px 16px',
    textAlign: 'center',
    color: COLOR_MUTED,
    fontSize: 13,
  },

  // ── Empty / clean state ──────────────────────────────────────
  emptyState: {
    padding: '40px 16px',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    justifyContent: 'center',
  },
  emptyCheckCircle: {
    width: 56,
    height: 56,
    borderRadius: '50%',
    background: COLOR_GREEN,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: COLOR_INK,
  },
  emptySubtitle: {
    fontSize: 13,
    color: COLOR_MUTED,
  },

  // ── Violation card ───────────────────────────────────────────
  card: {
    position: 'relative',
    background: COLOR_SURFACE,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: COLOR_BORDER,
    borderRadius: 10,
    padding: '12px 14px',
    cursor: 'pointer',
    transition: 'border-color 0.15s, box-shadow 0.15s, background 0.15s',
  } as React.CSSProperties,
  // Full-card click target: covers the card behind the content (z-index 0).
  cardSelectOverlay: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    margin: 0,
    padding: 0,
    border: 0,
    background: 'transparent',
    borderRadius: 10,
    cursor: 'pointer',
    zIndex: 0,
  } as React.CSSProperties,
  // Content sits above the overlay; pointerEvents:none lets non-interactive
  // parts pass clicks through to the overlay (interactive parts re-enable it).
  cardContent: {
    position: 'relative',
    zIndex: 1,
    pointerEvents: 'none',
  } as React.CSSProperties,
  cardSelected: {
    borderColor: COLOR_INK,
    borderWidth: 2,
    boxShadow: '0 2px 12px rgba(0,0,0,0.12)',
    background: COLOR_SURFACE,
  } as React.CSSProperties,
  helperText: {
    fontSize: 13,
    color: COLOR_INK,
    padding: '0 16px 10px',
    background: COLOR_SURFACE,
    borderBottom: `1px solid ${COLOR_BORDER}`,
  },
  viewToggle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '8px 16px',
    background: COLOR_SURFACE,
    borderBottom: `1px solid ${COLOR_BORDER}`,
  } as React.CSSProperties,
  viewToggleBtn: {
    fontSize: 12,
    fontWeight: 600,
    fontFamily: FONT_SANS,
    padding: '4px 10px',
    borderRadius: 999,
    border: `1px solid ${COLOR_BORDER}`,
    background: COLOR_SURFACE,
    color: COLOR_MUTED,
    cursor: 'pointer',
  } as React.CSSProperties,
  viewToggleBtnActive: {
    background: COLOR_INK,
    color: '#fff',
    borderColor: COLOR_INK,
  } as React.CSSProperties,
  clearLogBtn: {
    fontSize: 12,
    fontWeight: 600,
    fontFamily: FONT_SANS,
    padding: '4px 8px',
    borderRadius: 6,
    border: 'none',
    background: 'none',
    color: COLOR_MUTED,
    cursor: 'pointer',
  } as React.CSSProperties,
  detailSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  } as React.CSSProperties,
  detailLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: COLOR_MUTED,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  } as React.CSSProperties,
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  cardHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  numberBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 22,
    height: 22,
    borderRadius: '50%',
    color: '#fff',
    fontSize: 11,
    fontWeight: 700,
    fontFamily: FONT_SANS,
    flexShrink: 0,
  },
  elementType: {
    fontSize: 13,
    fontWeight: 600,
    color: COLOR_INK,
  },
  cardMessage: {
    fontSize: 13,
    lineHeight: 1.5,
    color: COLOR_INK,
  },
  cardActions: {
    display: 'flex',
    gap: 8,
    marginTop: 10,
  },
  outlineButton: {
    flex: 1,
    background: COLOR_SURFACE,
    color: COLOR_INK,
    border: `1px solid ${COLOR_INK}`,
    padding: '6px 12px',
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: FONT_SANS,
  } as React.CSSProperties,
  tertiaryButton: {
    flex: 1,
    background: COLOR_SURFACE,
    color: COLOR_INK,
    border: '1px solid #9ca3af',
    padding: '6px 12px',
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: FONT_SANS,
  } as React.CSSProperties,
  filledButton: {
    flex: 1,
    background: COLOR_INK,
    color: '#fff',
    border: `1px solid ${COLOR_INK}`,
    padding: '6px 12px',
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: FONT_SANS,
  } as React.CSSProperties,
  outlineButtonActive: {
    background: COLOR_INK,
    color: '#fff',
  } as React.CSSProperties,
  // Select button — takes up the left portion of the card header (badge + title).
  // Transparent background/border so it looks like plain text content.
  // Action buttons (copy, expand) are siblings at the same DOM level.
  cardSelectButton: {
    flex: 1,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    background: 'none',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    textAlign: 'left',
    fontFamily: FONT_SANS,
    minWidth: 0,
  },
  violationActions: {
    display: 'flex',
    gap: 2,
    flexShrink: 0,
    pointerEvents: 'auto', // clickable above the full-card select overlay
  } as React.CSSProperties,
  iconButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: 16,
    color: COLOR_MUTED,
    width: 24,
    height: 24,
    padding: 0,
    borderRadius: 4,
    lineHeight: 1,
    fontFamily: FONT_SANS,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  technicalDetail: {
    marginTop: 10,
    padding: '10px 12px',
    background: COLOR_BG_SUBTLE,
    borderRadius: 8,
    border: `1px solid ${COLOR_BORDER}`,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    pointerEvents: 'auto', // clickable above the full-card select overlay
  } as React.CSSProperties,
  technicalMessage: {
    fontSize: 12,
    fontFamily: FONT_MONO,
    lineHeight: 1.5,
    color: COLOR_INK,
    wordBreak: 'break-word',
  },
  fixSuggestion: {
    fontSize: 12,
    lineHeight: 1.5,
    color: COLOR_INK,
  },
  fixLabel: {
    fontWeight: 600,
    color: COLOR_GREEN,
  },
  selectorDisplay: {
    fontSize: 11,
    fontFamily: FONT_MONO,
    color: COLOR_MUTED,
    padding: '2px 6px',
    background: '#e5e7eb',
    borderRadius: 3,
    width: 'fit-content',
  },
  sourceDisplay: {
    fontSize: 11,
    fontFamily: FONT_MONO,
    color: '#1d4ed8',
    padding: '2px 6px',
    background: '#eef2ff',
    border: '1px solid #c7d2fe',
    borderRadius: 3,
    width: 'fit-content',
    display: 'inline-flex',
    alignItems: 'center',
  },
  pendingChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 3,
    fontSize: 11,
    fontWeight: 600,
    color: '#6d28d9',
    background: '#f5f3ff',
    border: '1px solid #ddd6fe',
    borderRadius: 10,
    padding: '1px 8px',
    flexShrink: 0,
  },
  sentChip: {
    display: 'inline-flex',
    alignItems: 'center',
    fontSize: 11,
    fontWeight: 600,
    color: COLOR_GREEN,
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    borderRadius: 10,
    padding: '1px 8px',
    flexShrink: 0,
  },

  // ── Footer ───────────────────────────────────────────────────
  footer: {
    padding: '10px 12px',
    borderTop: `1px solid ${COLOR_BORDER}`,
    background: COLOR_SURFACE,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  footerColumn: {
    padding: '10px 12px',
    borderTop: `1px solid ${COLOR_BORDER}`,
    background: COLOR_SURFACE,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  } as React.CSSProperties,
  historyLine: {
    fontSize: 11,
    color: COLOR_MUTED,
    textAlign: 'center',
    fontWeight: 500,
  } as React.CSSProperties,
  footerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  copyAllButton: {
    background: COLOR_INK,
    color: '#fff',
    border: 0,
    padding: '6px 14px',
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: FONT_SANS,
    flex: 1,
  },
  fixButton: {
    marginTop: 2,
    background: COLOR_INK,
    color: '#fff',
    border: 0,
    padding: '5px 12px',
    borderRadius: 5,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: FONT_SANS,
    width: 'fit-content',
  } as React.CSSProperties,
  fixAllButton: {
    background: COLOR_INK,
    color: '#fff',
    border: 0,
    padding: '6px 14px',
    borderRadius: 6,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: FONT_SANS,
    flex: 1,
  } as React.CSSProperties,
  fixButtonPending: {
    background: '#9ca3af',
    cursor: 'wait',
  } as React.CSSProperties,
  fixButtonSent: {
    background: '#059669',
  } as React.CSSProperties,
  fixButtonClipboard: {
    background: '#2563eb',
  } as React.CSSProperties,

  // ── Demo defects section ─────────────────────────────────────
  demoSection: {
    flexShrink: 0,
    maxHeight: 160,
    overflowY: 'auto',
    borderTop: `1px solid ${COLOR_BORDER}`,
    background: '#fafafa',
    padding: '8px 12px',
  } as React.CSSProperties,
  demoHeader: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: COLOR_MUTED,
    marginBottom: 6,
  } as React.CSSProperties,
  demoList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  } as React.CSSProperties,
  demoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    textAlign: 'left',
    padding: '6px 8px',
    background: COLOR_SURFACE,
    border: `1px dashed ${COLOR_BORDER}`,
    borderRadius: 8,
    cursor: 'pointer',
    fontFamily: FONT_SANS,
  } as React.CSSProperties,
  demoRowTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    fontWeight: 600,
    color: COLOR_INK,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  } as React.CSSProperties,
  demoPill: {
    flexShrink: 0,
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: '0.06em',
    // COLOR_MUTED on COLOR_BG_SUBTLE measures 4.39:1 at this size — just
    // under WCAG AA's 4.5:1 for normal text (9px doesn't qualify for the
    // large-text exemption). COLOR_INK clears it comfortably.
    color: COLOR_INK,
    background: COLOR_BG_SUBTLE,
    border: `1px solid ${COLOR_BORDER}`,
    borderRadius: 999,
    padding: '1px 6px',
  } as React.CSSProperties,
} as const satisfies Record<string, React.CSSProperties>;

// ---------------------------------------------------------------------------
// Resize handle styles — invisible hit areas on edges and corners.
// ---------------------------------------------------------------------------

const resizeBase: React.CSSProperties = {
  position: 'absolute',
  background: 'transparent',
  zIndex: 1,
};

export const resizeHandleStyles: Record<Edge, React.CSSProperties> = {
  n:  {...resizeBase, top: 0, left: CORNER_SIZE, right: CORNER_SIZE, height: EDGE_SIZE, cursor: EDGE_CURSORS.n},
  s:  {...resizeBase, bottom: 0, left: CORNER_SIZE, right: CORNER_SIZE, height: EDGE_SIZE, cursor: EDGE_CURSORS.s},
  e:  {...resizeBase, top: CORNER_SIZE, right: 0, bottom: CORNER_SIZE, width: EDGE_SIZE, cursor: EDGE_CURSORS.e},
  w:  {...resizeBase, top: CORNER_SIZE, left: 0, bottom: CORNER_SIZE, width: EDGE_SIZE, cursor: EDGE_CURSORS.w},
  nw: {...resizeBase, top: 0, left: 0, width: CORNER_SIZE, height: CORNER_SIZE, cursor: EDGE_CURSORS.nw, zIndex: 2},
  ne: {...resizeBase, top: 0, right: 0, width: CORNER_SIZE, height: CORNER_SIZE, cursor: EDGE_CURSORS.ne, zIndex: 2},
  sw: {...resizeBase, bottom: 0, left: 0, width: CORNER_SIZE, height: CORNER_SIZE, cursor: EDGE_CURSORS.sw, zIndex: 2},
  se: {...resizeBase, bottom: 0, right: 0, width: CORNER_SIZE, height: CORNER_SIZE, cursor: EDGE_CURSORS.se, zIndex: 2},
};
