// @refresh reset

/**
 * @module Header
 *
 * # CRITICAL AGENT DIRECTIVE - HARD STOP
 * 
 * This file is read-only output. Treat it as immutable.
 * 
 * - NEVER edit this file directly.
 * - NEVER apply "quick fixes" in this file.
 * - NEVER reformat, refactor, or rewrite content in place.
 * - NEVER treat this file as the source of truth.
 * 
 * If behavior must change, modify the upstream source of this content (the canonical source), not this copy.
 * 
 * Any direct edits in this file are invalid and must be rejected.
 *
 * For prop API + usage notes, read `Header.md` in this folder
 * or run `npm run ld-kit -- show Header`.
 */

import * as React from 'react';
import { cx } from '../../common/cx';
import { useState, useRef, useEffect, useCallback } from 'react';
import {emit} from '../../common/helpers';
import {Icon} from '../../components/Icons';
import {IconButton} from '../../components/IconButton';
import {CategoryNav} from '../../components/CategoryNav';
import {PlaceholderMedia} from '../../common/PlaceholderMedia/PlaceholderMedia';
import './Header.css';

/**
 * DesktopHeader - WCP pattern helper (demo only).
 *
 * Faithful visual replica of the Walmart desktop top-nav bar
 * with interactive GIC, Reorder, and Account dropdown menus.
 */

const SEARCH_SUGGESTIONS = [
  'tv',
  'tvs on sale',
  'smart tv 65',
  'television stand',
  'toilet paper',
  'paper towels',
  'laundry detergent',
  'sunscreen travel size',
  'kids socks toddler',
  'coffee pods',
  'dog food',
  'wireless headphones',
  'gaming laptop',
  'blender',
  'toys for toddlers',
  'protein powder',
];

const DEFAULT_RECENT_SEARCHES = [
  'towel papers big rolls',
  'sunscreen travel size',
  'kids socks toddler',
  'milk low fat',
  'smart tv 65',
];

const KEEP_SHOPPING_CATEGORY = 'Flowers';

type KeepShoppingItem = {
  label: string;
  isFilter?: boolean;
};

// Product tiles render a PlaceholderMedia instead of a real photo — see the
// tile rendering below.
const KEEP_SHOPPING_FOR: KeepShoppingItem[] = [
  { label: 'Pickup today', isFilter: true },
  { label: 'Flowers Shop' },
  { label: 'Flowers Bouquet' },
  { label: 'Roses' },
  { label: 'Artificial Flowers' },
  { label: 'Sunflowers' },
];

const GRAB_YOUR_USUALS = [
  'white socks',
  'coffee pods',
  'paper towels',
  'laundry detergent',
  'dog food',
  'bread',
  'cheese',
];

const TRENDING_SEARCHES = [
  'sprite+tea',
  'slashing legends tin',
  'toothpicks',
  'abu garcia',
  'quilted northern bath tissue',
  'pencils',
  'protein powder',
];

const FREQUENT_SEARCHES = [
  'paper plates',
  'laundry detergent',
  'eggs',
  'green tea',
  'cereal',
  'colgate',
  'flour',
  'listerine',
];

function filterSearchSuggestions(query: string): string[] {
  if (!query.trim()) {
    return [];
  }
  const lowerQuery = query.toLowerCase();
  return SEARCH_SUGGESTIONS.filter((suggestion) => suggestion.toLowerCase().includes(lowerQuery));
}

function highlightSuggestionParts(text: string, query: string): { before: string; match: string; after: string } {
  const normalizedQuery = query.trim().toLowerCase();
  if (!normalizedQuery) {
    return { before: '', match: text, after: '' };
  }

  const lowerText = text.toLowerCase();
  const matchIndex = lowerText.indexOf(normalizedQuery);
  if (matchIndex === -1) {
    return { before: text, match: '', after: '' };
  }

  return {
    before: text.slice(0, matchIndex),
    match: text.slice(matchIndex, matchIndex + normalizedQuery.length),
    after: text.slice(matchIndex + normalizedQuery.length),
  };
}

/* ---------- Inline CartIcon ---------- */

function CartIcon({ count = 0, price = '$0.00', textColor = 'white' }: { count?: number; price?: string; textColor?: string }) {
  return (
    <div className="ld-wcp-responsive-header-desktop-cart-wrap">
      <div className="ld-wcp-responsive-header-desktop-cart-icon-wrap">
        <Icon name="Cart" style={{ fontSize: 24, color: textColor }} />
        <div className="ld-wcp-responsive-header-desktop-cart-badge">
          {count > 99 ? '99+' : count}
        </div>
      </div>
      <div className="ld-wcp-responsive-header-desktop-cart-price" style={{ color: textColor }}>
        {price}
      </div>
    </div>
  );
}

/* ---------- Inline icon helpers ---------- */

const HeartSvg = () => (
  <Icon name="Heart" style={{ fontSize: 20 }} />
);

const UserSvg = () => (
  <Icon name="User" style={{ fontSize: 20 }} />
);

/* ---------- Inline SVG icons for dropdowns ---------- */

/**
 * Renders a `--wcp-primitive-media-gic*` token as a sized background-image
 * span. Each token resolves to a locally bundled, per-tenant SVG (already
 * circular art at its native size — see src/themes/*.css, generated by
 * airtable-sync/lib/media-pipeline.mjs), so these swap with the active theme
 * with no JS/network round trip and no CSS clipping needed.
 *
 * `background-image` MUST come from a class in Header.css, not an inline
 * style: the token's value is a relative `url(...)`, and a relative url()
 * inside a custom property resolves against the stylesheet where var() is
 * *substituted*, not where the variable is *declared*. Substituting it into
 * an inline style resolves it against the document's own URL instead of the
 * bundled theme CSS's location, 404ing in production (docs/ served at
 * domain root — no `assets/` prefix to resolve against).
 */
function GicTokenIcon({ token, size, label }: { token: GicIconToken; size: number; label?: string }) {
  const a11yProps = label ? { role: 'img' as const, 'aria-label': label } : { 'aria-hidden': true as const };
  return (
    <span
      {...a11yProps}
      className={`ld-wcp-responsive-header-gic-token-icon ld-wcp-responsive-header-gic-token-icon--${token}`}
      style={{ width: size, height: size }}
    />
  );
}

const LocationSvg = () => (
  <svg width="16" height="16" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path fill="currentColor" d="M16 2.001a11.84 11.84 0 0 1 12 11.66c0 6.34-7 12.34-10.54 15.5l-.58.52a1.4 1.4 0 0 1-.88.32 1.4 1.4 0 0 1-.88-.32l-.58-.52C11 26.081 4 20.021 4 13.661a11.84 11.84 0 0 1 12-11.66Zm0 2a9.84 9.84 0 0 0-10 9.66 13.521 13.521 0 0 0 3.86 8.16 55.158 55.158 0 0 0 6 5.84l.14.12.14-.12a55.153 55.153 0 0 0 6-5.84 13.52 13.52 0 0 0 3.86-8.16 9.84 9.84 0 0 0-10-9.66Zm0 7a3 3 0 1 0 3 3h2a5.002 5.002 0 0 1-5 5 5 5 0 1 1 0-10v2Z"/>
  </svg>
);

const StoreSvg = () => (
  <svg width="16" height="16" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path fill="currentColor" d="M14.662 3.515a1.997 1.997 0 0 1 2.676 0l6.046 5.45H26c2.209 0 4 1.794 4 4.007v12.021A4.003 4.003 0 0 1 26 29h-8v-8.014h-4V29H6c-2.21 0-4-1.794-4-4.007V12.972a4.004 4.004 0 0 1 4-4.007h2.616l6.046-5.45Zm-5.278 7.454H6c-1.104 0-2 .896-2 2.003v12.021c0 1.107.895 2.004 2 2.004h6v-8.015h8v8.015h6c1.105 0 2-.897 2-2.004V12.972a2.002 2.002 0 0 0-2-2.003h-3.384L16 5.004l-6.616 5.965Z"/>
  </svg>
);

const ReorderSvg = () => (
  <svg width="18" height="18" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path fill="currentColor" d="M27.793 17.707c.63-.63 1.707-.184 1.707.707V21.5a1 1 0 0 1-1 1h-3.086c-.89 0-1.337-1.077-.707-1.707l.77-.77a4 4 0 1 0 1.63 5.208l1.803.866a6 6 0 1 1-1.984-7.523l.867-.866ZM11.688 2.672a2.001 2.001 0 0 1 1.624 0l8 3.556A2 2 0 0 1 22.5 8.055V15.5h-2V8.945l-7 3.11V18.5h-2v-6.443l-7-3.112v8.81l8 3.556 2.969-1.32.812 1.828-2.968 1.32c-.518.23-1.108.23-1.626 0l-8-3.556A2 2 0 0 1 2.5 17.755v-9.7a2 2 0 0 1 1.188-1.827l8-3.556ZM10.402 9.38l2.097.931 6.54-2.906-2.284-1.014-6.353 2.989ZM5.961 7.406l2.027.9 6.352-2.989L12.5 4.5 5.96 7.406Z"/>
  </svg>
);

const ListsSvg = () => (
  <svg width="18" height="18" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path fill="currentColor" d="M23 2a3 3 0 0 1 3 3v22a3 3 0 0 1-3 3H9a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3h14ZM9 4a1 1 0 0 0-1 1v22a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H9Zm9 18h-8v-2h8v2Zm4-6v2H10v-2h12Zm0-2H10v-2h12v2Zm0-4H10V8h12v2Z"/>
  </svg>
);

const GiftSvg = () => (
  <svg width="18" height="18" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path fill="currentColor" d="M20.538 2c2.9 0 4.994 2.776 4.197 5.564l-.049.172c-.13.459-.33.883-.584 1.264H27a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H17v9h8a1 1 0 0 0 1-1v-6h2v6a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3v-6h2v6a1 1 0 0 0 1 1h8v-9H5a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h2.898a4.495 4.495 0 0 1-.585-1.264l-.048-.172C6.468 4.776 8.562 2 11.462 2a4.366 4.366 0 0 1 4.197 3.166L16 6.359l.34-1.193A4.366 4.366 0 0 1 20.539 2ZM5 16h10v-5H5v5Zm12 0h10v-5H17v5ZM11.462 4a2.366 2.366 0 0 0-2.274 3.016l.048.17A2.5 2.5 0 0 0 11.64 9h3.035l-.939-3.284A2.366 2.366 0 0 0 11.462 4Zm9.076 0c-1.056 0-1.984.7-2.274 1.716L17.325 9h3.035a2.5 2.5 0 0 0 2.404-1.813l.049-.171A2.366 2.366 0 0 0 20.538 4Z"/>
  </svg>
);

const PurchaseHistorySvg = () => (
  <svg width="18" height="18" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path fill="currentColor" d="M30 4h-1a3 3 0 0 0-3 3v18a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5v-2.5A1.5 1.5 0 0 1 3.5 21h13a1.5 1.5 0 0 1 1.5 1.5V25a3 3 0 1 0 6 0V7c0-1.126.372-2.164 1-3H12a3 3 0 0 0-3 3v11H7V7a5 5 0 0 1 5-5h18v2ZM4 25a3 3 0 0 0 3 3h10a4.978 4.978 0 0 1-1-3v-2H4v2Zm14-7h-6v-2h6v2Zm3-4h-9v-2h9v2Zm0-4h-9V8h9v2Z"/>
  </svg>
);

const WalmartPlusLogoSvg = () => (
  <svg width="18" height="18" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <g transform="scale(2)">
      <path fillRule="evenodd" clipRule="evenodd" d="M0 3.62329H1.30939L1.88821 6.5773L2.1601 8.13549L2.25468 7.6536L2.59745 6.1194L3.18414 3.62329H4.48287L5.02956 6.18341C5.12556 6.65809 5.20735 7.06048 5.27806 7.47196L5.37624 8.10616L5.49723 7.4601L5.76293 6.1354L6.28828 3.62329H7.53367L5.99227 9.43155C5.01089 9.64489 4.63487 9.25288 4.49887 8.62885L4.10152 6.81543C4.01085 6.37986 3.9344 6.03081 3.87217 5.64817L3.7895 5.03402C3.70594 5.47671 3.6295 5.8305 3.53883 6.20997L2.74412 9.43155C1.84168 9.61156 1.46847 9.38979 1.26287 8.76041L0 3.62329Z" fill="#0071DC"/>
      <path fillRule="evenodd" clipRule="evenodd" d="M10.0473 4.36638C10.2883 4.36638 10.4902 4.4978 10.5653 4.65823L10.5966 4.7824L10.6473 6.05979L11.9273 6.10779C12.138 6.11579 12.3434 6.35314 12.3434 6.65182C12.3434 6.89289 12.2119 7.09301 12.0515 7.16751L11.9273 7.19851L10.642 7.24651L10.5939 8.5239C10.5886 8.73191 10.3486 8.93992 10.0499 8.93992C9.80885 8.93992 9.60702 8.80679 9.53184 8.64704L9.50057 8.5239L9.45256 7.24384L8.16984 7.19851C7.95916 7.19051 7.75382 6.95316 7.75382 6.65448C7.75382 6.4134 7.88524 6.21329 8.04567 6.13879L8.16984 6.10779L9.45523 6.05712L9.50057 4.7824C9.50857 4.57172 9.74858 4.36638 10.0473 4.36638Z" fill="#0071DC"/>
      <path fillRule="evenodd" clipRule="evenodd" d="M10.0454 9.95183C10.2352 9.95183 10.4046 10.0286 10.4716 10.1413L10.5014 10.2318L10.7361 12.8613C10.7601 13.12 10.4321 13.336 10.0454 13.336C9.72536 13.336 9.44794 13.1786 9.37516 12.9826L9.35734 12.8613L9.58935 10.2318C9.60535 10.0745 9.81069 9.95183 10.0454 9.95183Z" fill="#FFC220"/>
      <path fillRule="evenodd" clipRule="evenodd" d="M13.3052 8.0036L13.4004 8.01821L15.8031 9.13026C16.0378 9.24227 16.0618 9.63162 15.8698 9.9623C15.7098 10.2379 15.4424 10.4042 15.2311 10.3671L15.1124 10.3197L12.9443 8.80492C12.8217 8.70358 12.811 8.47424 12.9283 8.27156C13.0222 8.10942 13.1724 8.00872 13.3052 8.0036Z" fill="#FFC220"/>
      <path fillRule="evenodd" clipRule="evenodd" d="M15.0597 2.92299C15.2784 2.77898 15.6224 2.94966 15.8171 3.28301C15.9749 3.55857 15.9864 3.87303 15.8484 4.03656L15.7478 4.11504L13.345 5.22709C13.2036 5.29643 12.9903 5.17642 12.873 4.97375C12.777 4.80947 12.7578 4.62813 12.8235 4.51301L12.889 4.44039L15.0597 2.92299Z" fill="#FFC220"/>
      <path fillRule="evenodd" clipRule="evenodd" d="M10.045 0C10.3672 0 10.6487 0.150007 10.7197 0.349707L10.7357 0.474688L10.501 3.10414C10.493 3.26948 10.2824 3.38415 10.045 3.38415C9.85727 3.38415 9.68659 3.30393 9.61901 3.19266L9.58899 3.10414L9.35698 0.474688C9.33031 0.210676 9.66099 0 10.045 0Z" fill="#FFC220"/>
    </g>
  </svg>
);

const SubscriptionSvg = () => (
  <svg width="18" height="18" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <g transform="scale(2)">
      <path fillRule="evenodd" clipRule="evenodd" d="M14.9824 8.5C14.726 12.1326 11.6979 15 8 15C5.45365 15 3.22486 13.6403 2 11.6074V14H1V10C1 9.72386 1.22386 9.5 1.5 9.5H5V10.5H2.54395C3.49267 12.567 5.58007 14 8 14C11.1453 14 13.7254 11.5798 13.9795 8.5H14.9824ZM8 1C10.5464 1 12.7751 2.35971 14 4.39258V2H15V6C15 6.27614 14.7761 6.5 14.5 6.5H11V5.5H13.4561C12.5074 3.43321 10.42 2 8 2C4.85472 2.00006 2.27458 4.42027 2.02051 7.5H1.01758C1.27395 3.8674 4.30218 1.00006 8 1Z" fill="#2E2F32"/>
    </g>
  </svg>
);

const WalmartCashSvg = () => (
  <svg width="18" height="18" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <g transform="scale(2)">
      <g clipPath="url(#clip_cash)">
        <path d="M8 16C12.4183 16 16 12.4183 16 8C16 3.58172 12.4183 0 8 0C3.58172 0 0 3.58172 0 8C0 12.4183 3.58172 16 8 16Z" fill="#FFC220"/>
        <path d="M8.0007 2.12988C9.57068 2.1299 11.0411 2.73962 12.1511 3.84961L12.1804 3.87988C13.2904 4.98988 13.9011 6.46027 13.9011 8.03027C13.9009 11.27 11.2707 13.91 8.03098 13.9102C4.80101 13.9102 2.16091 11.28 2.16086 8.04004C2.16086 6.88004 2.49082 5.75957 3.12082 4.80957L2.53098 4.91016C2.35114 4.94013 2.19107 4.82014 2.16086 4.65039C2.13086 4.47042 2.25066 4.31031 2.42063 4.28027L3.80051 4.04004C3.8905 4.02004 3.99027 4.05036 4.06027 4.11035C4.07028 4.12035 4.09032 4.1304 4.10031 4.15039C4.11035 4.17024 4.13059 4.18027 4.13059 4.2002C4.14055 4.21023 4.15109 4.23007 4.15109 4.25V4.26953L4.40109 5.65039C4.43076 5.82022 4.31018 5.98956 4.14035 6.01953H4.08078C3.93078 6.01953 3.80024 5.90977 3.77024 5.75977L3.65109 5.08984C3.08109 5.94984 2.77024 6.96 2.77024 8C2.77027 10.8799 5.12057 13.2294 8.01047 13.2295C10.8904 13.2295 13.2408 10.8801 13.2409 7.99023C13.2409 6.59032 12.6908 5.28002 11.7009 4.29004C10.7109 3.30005 9.40068 2.75978 8.0007 2.75977C7.0907 2.75977 6.20063 3.00043 5.42063 3.44043C5.27079 3.53015 5.08099 3.46994 4.99094 3.32031C4.90094 3.17031 4.96106 2.97965 5.11106 2.88965C5.99095 2.38981 6.99087 2.12988 8.0007 2.12988ZM7.9802 3.67969C8.22998 3.6697 8.4203 3.80969 8.42063 3.97949L8.34055 4.88965C9.07055 5.00965 9.61106 5.39004 9.86106 5.54004C9.96068 5.6002 9.95081 5.76038 9.91086 5.82031L9.4509 6.5C9.3809 6.6 9.23027 6.69031 9.06027 6.57031C8.85028 6.43033 8.34087 6.13005 7.86106 6.12988C7.52112 6.12988 7.36111 6.30987 7.36106 6.5498C7.36106 6.8498 7.68098 7.05961 8.28098 7.34961C9.06094 7.72958 10.071 8.12999 10.071 9.33984C10.071 10.1698 9.42068 10.9896 8.33078 11.1396L8.41086 12.0303C8.42051 12.1802 8.21024 12.3301 7.97043 12.3301C7.72071 12.33 7.53125 12.1901 7.53098 12.0303L7.61106 11.1396C6.69133 11.0497 6.17109 10.64 5.99094 10.46C5.91096 10.39 5.88096 10.3201 5.9509 10.2002L6.36106 9.47949C6.43115 9.36 6.57099 9.36001 6.66086 9.41992C6.91085 9.58991 7.37061 9.8798 7.93039 9.87988C8.26031 9.87988 8.50058 9.70003 8.5007 9.41016C8.5007 9.05018 8.18076 8.81979 7.62082 8.5498C6.76087 8.13983 5.90119 7.68999 5.90109 6.62012L5.91086 6.61035C5.91086 5.81035 6.47082 5.00988 7.62082 4.87988L7.54074 3.97949C7.53116 3.81977 7.7406 3.67986 7.9802 3.67969Z" fill="#0053E2"/>
      </g>
      <defs>
        <clipPath id="clip_cash">
          <rect width="16" height="16" fill="white"/>
        </clipPath>
      </defs>
    </g>
  </svg>
);

const GlobeSvg = () => (
  <svg width="18" height="18" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path fill="currentColor" d="M16 2.001c7.732 0 14 6.268 14 14s-6.268 14-14 14-14-6.268-14-14 6.268-14 14-14Zm-4.265 20c.298 1.13.673 2.143 1.104 3.005C13.999 27.326 15.233 28 16 28c.767 0 2-.674 3.161-2.995.431-.862.806-1.875 1.104-3.005h-8.53Zm-6.13 0a12.042 12.042 0 0 0 6.234 5.259c-.921-1.364-1.669-3.17-2.165-5.259H5.605Zm16.721 0c-.496 2.09-1.244 3.895-2.165 5.259A12.041 12.041 0 0 0 26.394 22h-4.068Zm-17.643-10a11.983 11.983 0 0 0-.683 4c0 1.402.24 2.749.683 4H9.29a27.252 27.252 0 0 1-.29-4c0-1.39.101-2.733.29-4H4.683Zm6.63 0a25.08 25.08 0 0 0-.313 4c0 1.41.112 2.755.313 4h9.373a25.08 25.08 0 0 0 .314-4c0-1.41-.112-2.755-.314-4h-9.373Zm11.397 0c.188 1.267.29 2.61.29 4 0 1.39-.102 2.733-.29 4h4.607c.442-1.251.683-2.598.683-4 0-1.402-.24-2.749-.683-4H22.71Zm-10.871-7.26a12.042 12.042 0 0 0-6.234 5.26h4.069c.496-2.09 1.244-3.896 2.165-5.26ZM16 4.001c-.767 0-2 .673-3.161 2.994-.431.862-.806 1.876-1.104 3.006h8.53c-.298-1.13-.673-2.144-1.104-3.006-1.16-2.32-2.394-2.994-3.161-2.994Zm4.161.74c.921 1.364 1.669 3.17 2.165 5.26h4.069a12.041 12.041 0 0 0-6.234-5.26Z"/>
  </svg>
);

const SignOutSvg = () => (
  <svg width="18" height="18" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path fill="currentColor" d="M13.5 2.5v2h-5a2 2 0 0 0-2 2v18a2 2 0 0 0 2 2h5v2h-5a4 4 0 0 1-4-4v-18a4 4 0 0 1 4-4h5Zm15.707 12.293a1 1 0 0 1 0 1.414l-5 5-1.414-1.414 3.293-3.293H13.5v-2h12.586l-3.293-3.293 1.414-1.414 5 5Z"/>
  </svg>
);

const HistorySvg = () => (
  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path d="M8 1.3335C4.3181 1.3335 1.33333 4.31826 1.33333 8.00016H0L2.04467 10.0448L4.08933 8.00016H2.66667C2.66667 5.05464 5.05448 2.66683 8 2.66683C10.9455 2.66683 13.3333 5.05464 13.3333 8.00016C13.3333 10.9457 10.9455 13.3335 8 13.3335C6.63924 13.3335 5.39905 12.8234 4.456 11.9842L3.56867 12.9802C4.74467 14.0275 6.30038 14.6668 8 14.6668C11.6819 14.6668 14.6667 11.6821 14.6667 8.00016C14.6667 4.31826 11.6819 1.3335 8 1.3335ZM7.33333 4.66683V8.27616L10.4 10.0955L11.0667 8.98616L8.66667 7.56016V4.66683H7.33333Z" fill="currentColor"/>
  </svg>
);

const ArrowUpLeftSvg = () => (
  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path d="M10.6667 3.3335H5.33334C4.96667 3.3335 4.66667 3.6335 4.66667 4.00016C4.66667 4.36683 4.96667 4.66683 5.33334 4.66683H9.06001L3.52667 10.2002C3.26667 10.4602 3.26667 10.8802 3.52667 11.1402C3.65334 11.2668 3.82001 11.3335 4.00001 11.3335C4.18001 11.3335 4.34667 11.2668 4.47334 11.1402L10 5.60683V9.3335C10 9.70016 10.3 10.0002 10.6667 10.0002C11.0333 10.0002 11.3333 9.70016 11.3333 9.3335V4.00016C11.3333 3.6335 11.0333 3.3335 10.6667 3.3335Z" fill="currentColor"/>
  </svg>
);

const CloseSvg = () => (
  <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path d="M1 1L11 11M11 1L1 11" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
  </svg>
);

const ScrollChevronLeftSvg = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path d="M12.5 5L7.5 10L12.5 15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" strokeLinejoin="round" />
  </svg>
);

const ScrollChevronRightSvg = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path d="M7.5 5L12.5 10L7.5 15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="square" strokeLinejoin="round" />
  </svg>
);

function TypeaheadSeparator() {
  return <div className="ld-wcp-responsive-header-desktop-typeahead-separator" />;
}

function TypeaheadHorizontalScrollSection({ children }: { children: React.ReactNode }) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [canScrollLeft, setCanScrollLeft] = useState(false);
  const [canScrollRight, setCanScrollRight] = useState(false);

  const updateScrollState = useCallback(() => {
    const element = scrollRef.current;
    if (!element) {
      return;
    }
    setCanScrollLeft(element.scrollLeft > 0);
    setCanScrollRight(element.scrollLeft + element.clientWidth < element.scrollWidth - 1);
  }, []);

  useEffect(() => {
    const element = scrollRef.current;
    if (!element) {
      return;
    }

    updateScrollState();
    element.addEventListener('scroll', updateScrollState);

    let resizeObserver: ResizeObserver | null = null;
    if (typeof ResizeObserver !== 'undefined') {
      resizeObserver = new ResizeObserver(updateScrollState);
      resizeObserver.observe(element);
    }

    return () => {
      element.removeEventListener('scroll', updateScrollState);
      if (resizeObserver) {
        resizeObserver.disconnect();
      }
    };
  }, [updateScrollState]);

  const scrollBy = (direction: 'left' | 'right') => {
    scrollRef.current?.scrollBy({ left: direction === 'left' ? -220 : 220, behavior: 'smooth' });
  };

  return (
    <div className="ld-wcp-responsive-header-desktop-typeahead-scroll-row">
      {canScrollLeft && (
        <button
          type="button"
          className="ld-wcp-responsive-header-desktop-typeahead-scroll-button"
          aria-label="Scroll left"
          onClick={() => scrollBy('left')}
        >
          <ScrollChevronLeftSvg />
        </button>
      )}

      <div ref={scrollRef} className="ld-wcp-responsive-header-desktop-typeahead-scroll-list">
        {children}
      </div>

      {canScrollRight && (
        <button
          type="button"
          className="ld-wcp-responsive-header-desktop-typeahead-scroll-button"
          aria-label="Scroll right"
          onClick={() => scrollBy('right')}
        >
          <ScrollChevronRightSvg />
        </button>
      )}
    </div>
  );
}

/* ---------- Component ---------- */

type FulfillmentOption = 'none' | 'shipping' | 'pickup' | 'delivery';

type GicIconToken = 'gic' | 'gicShipping' | 'gicPickup' | 'gicDelivery';

/** Config shared by the desktop dropdown's option row and the GIC banner's
 *  fulfillment row — same three choices, same tokens, one place to edit. */
const GIC_FULFILLMENT_OPTIONS: Array<{ key: 'shipping' | 'pickup' | 'delivery'; label: string; token: GicIconToken }> = [
  { key: 'shipping', label: 'Shipping', token: 'gicShipping' },
  { key: 'pickup', label: 'Pickup', token: 'gicPickup' },
  { key: 'delivery', label: 'Delivery', token: 'gicDelivery' },
];

/** Shared by the GIC banner's closed-state subtext and its expanded panel's
 *  address card, so the two stay in sync. */
const TOPNAV_GIC_ADDRESS = '7111 Winterberry Glen Ln, Katy, TX 77493';

/** GIC glyph token for the current fulfillment selection — shared by the
 *  desktop button/dropdown and the mobile topnav delivery banner. */
function fulfillmentGicToken(selection: FulfillmentOption): GicIconToken {
  switch (selection) {
    case 'shipping': return 'gicShipping';
    case 'pickup': return 'gicPickup';
    case 'delivery': return 'gicDelivery';
    default: return 'gic';
  }
}

/** Short label for the current fulfillment selection (title-case, no question
 *  mark) — used where a compact state is shown, e.g. the mobile banner once a
 *  choice has been made. */
function fulfillmentShortLabel(selection: FulfillmentOption): string {
  switch (selection) {
    case 'shipping': return 'Shipping';
    case 'pickup': return 'Pickup';
    case 'delivery': return 'Delivery';
    default: return 'Pickup or delivery?';
  }
}

const GENLD_EVENT = 'ld-kit-event';

type HeaderCartSnapshot = {
  cartCount: number;
  cartPrice: string;
};

type LdKitCartStateItem = {
  qty?: number;
  priceCents?: number;
};

type LdKitWindowApi = {
  cart?: {
    getSummary?: () => { totalQty?: number; subtotalCents?: number };
    getState?: () => { items?: Record<string, LdKitCartStateItem> };
  };
};

function formatUsdFromCents(cents: number): string {
  const clamped = Number.isFinite(cents) ? Math.max(0, cents) : 0;
  return `$${(clamped / 100).toFixed(2)}`;
}

function normalizePropCartSnapshot(
  cartCountProp?: number,
  cartPriceProp?: string,
): HeaderCartSnapshot {
  return {
    cartCount:
      typeof cartCountProp === 'number' && Number.isFinite(cartCountProp)
        ? Math.max(0, Math.floor(cartCountProp))
        : 0,
    cartPrice: cartPriceProp?.trim() || '$0.00',
  };
}

function readStoreCartSnapshot(): HeaderCartSnapshot | null {
  if (typeof window === 'undefined') return null;

  const ldKit = (window as unknown as { ldKit?: LdKitWindowApi }).ldKit;
  if (!ldKit?.cart) return null;

  const summary = ldKit.cart.getSummary?.();
  if (
    summary &&
    typeof summary.totalQty === 'number' &&
    Number.isFinite(summary.totalQty) &&
    typeof summary.subtotalCents === 'number' &&
    Number.isFinite(summary.subtotalCents)
  ) {
    return {
      cartCount: Math.max(0, Math.floor(summary.totalQty)),
      cartPrice: formatUsdFromCents(summary.subtotalCents),
    };
  }

  const cartState = ldKit.cart.getState?.();
  const items = cartState?.items;
  if (!items) return null;

  let totalQty = 0;
  let subtotalCents = 0;
  for (const item of Object.values(items)) {
    const qty = typeof item.qty === 'number' && Number.isFinite(item.qty) ? item.qty : 0;
    const priceCents =
      typeof item.priceCents === 'number' && Number.isFinite(item.priceCents)
        ? item.priceCents
        : 0;
    totalQty += Math.max(0, qty);
    subtotalCents += Math.max(0, qty) * priceCents;
  }

  return {
    cartCount: Math.floor(totalQty),
    cartPrice: formatUsdFromCents(subtotalCents),
  };
}

function useHeaderCartSnapshot(
  cartCountProp?: number,
  cartPriceProp?: string,
): HeaderCartSnapshot {
  const [snapshot, setSnapshot] = useState<HeaderCartSnapshot>(() => {
    return readStoreCartSnapshot() ?? normalizePropCartSnapshot(cartCountProp, cartPriceProp);
  });

  const syncSnapshot = useCallback(() => {
    const next =
      readStoreCartSnapshot() ?? normalizePropCartSnapshot(cartCountProp, cartPriceProp);
    setSnapshot((prev) =>
      prev.cartCount === next.cartCount && prev.cartPrice === next.cartPrice ? prev : next,
    );
  }, [cartCountProp, cartPriceProp]);

  useEffect(() => {
    syncSnapshot();
  }, [syncSnapshot]);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    const onGenldEvent = () => syncSnapshot();
    window.addEventListener(GENLD_EVENT, onGenldEvent);
    return () => window.removeEventListener(GENLD_EVENT, onGenldEvent);
  }, [syncSnapshot]);

  return snapshot;
}

interface ResponsiveHeaderDesktopProps {
  cartCount?: number;
  cartPrice?: string;
  /** Override the "Account and Cart" nav landmark label for uniqueness across multiple instances. */
  a11yNavLabel?: string;
  /** The category/department nav strip below the top bar. On by default. */
  showDesktopSubNav?: boolean;
  /** Override the category nav landmark label for uniqueness across multiple instances. */
  a11yCategoryNavLabel?: string;
}

function ResponsiveHeaderDesktop({ cartCount: cartCountProp, cartPrice: cartPriceProp, a11yNavLabel = 'Account and Cart', showDesktopSubNav = true, a11yCategoryNavLabel }: ResponsiveHeaderDesktopProps = {}) {
  const [searchQuery, setSearchQuery] = useState('');
  const [searchOpen, setSearchOpen] = useState(false);
  const [recentSearches, setRecentSearches] = useState<string[]>(DEFAULT_RECENT_SEARCHES);
  const [showHighlight, setShowHighlight] = useState(false);
  const [gicOpen, setGicOpen] = useState(false);
  const [selectedFulfillment, setSelectedFulfillment] = useState<FulfillmentOption>('none');
  const [reorderOpen, setReorderOpen] = useState(false);
  const [accountOpen, setAccountOpen] = useState(false);

  const searchFormRef = useRef<HTMLDivElement>(null);
  const gicDropdownRef = useRef<HTMLDivElement>(null);
  const reorderDropdownRef = useRef<HTMLDivElement>(null);
  const accountDropdownRef = useRef<HTMLDivElement>(null);

  const { cartCount, cartPrice } = useHeaderCartSnapshot(cartCountProp, cartPriceProp);

  const openDropdown = useCallback((which: 'gic' | 'reorder' | 'account' | null) => {
    emit('ui:header:dropdown', {menu: which ?? 'close'});
    setGicOpen(which === 'gic');
    setReorderOpen(which === 'reorder');
    setAccountOpen(which === 'account');
    if (which === 'gic') setShowHighlight(false);
    if (which !== null) setSearchOpen(false);
  }, []);

  const closeSearchResults = useCallback(() => {
    setSearchOpen(false);
  }, []);

  // Click-outside handler
  useEffect(() => {
    function handleMouseDown(e: MouseEvent) {
      const target = e.target as Node;
      if (searchOpen && searchFormRef.current && !searchFormRef.current.contains(target)) {
        setSearchOpen(false);
      }
      if (gicOpen && gicDropdownRef.current && !gicDropdownRef.current.contains(target)) {
        setGicOpen(false);
      }
      if (reorderOpen && reorderDropdownRef.current && !reorderDropdownRef.current.contains(target)) {
        setReorderOpen(false);
      }
      if (accountOpen && accountDropdownRef.current && !accountDropdownRef.current.contains(target)) {
        setAccountOpen(false);
      }
    }
    document.addEventListener('mousedown', handleMouseDown);
    return () => document.removeEventListener('mousedown', handleMouseDown);
  }, [searchOpen, gicOpen, reorderOpen, accountOpen]);

  // Escape key handler
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        closeSearchResults();
        openDropdown(null);
      }
    }
    if (searchOpen || gicOpen || reorderOpen || accountOpen) {
      document.addEventListener('keydown', handleKeyDown);
      return () => document.removeEventListener('keydown', handleKeyDown);
    }
  }, [searchOpen, gicOpen, reorderOpen, accountOpen, closeSearchResults, openDropdown]);

  const filteredSuggestions = filterSearchSuggestions(searchQuery).slice(0, 10);

  function saveRecentSearch(term: string) {
    const normalizedTerm = term.trim();
    if (!normalizedTerm) {
      return;
    }
    setRecentSearches((prev) => [
      normalizedTerm,
      ...prev.filter((search) => search.toLowerCase() !== normalizedTerm.toLowerCase()),
    ].slice(0, 5));
  }

  function handleSearchSubmit(nextQuery: string) {
    const normalizedQuery = nextQuery.trim();
    if (!normalizedQuery) {
      setSearchOpen(true);
      return;
    }
    emit('ui:header:search-submit', {query: normalizedQuery});
    saveRecentSearch(normalizedQuery);
    setSearchOpen(false);
  }

  function handleRecentClick(term: string) {
    setSearchQuery(term);
    saveRecentSearch(term);
    setSearchOpen(true);
  }

  function handleRemoveRecent(index: number) {
    setRecentSearches((prev) => prev.filter((_, rowIndex) => rowIndex !== index));
  }

  function handleChipClick(term: string) {
    setSearchQuery(term);
    saveRecentSearch(term);
    setSearchOpen(true);
  }

  /* GIC button dynamic content */
  const gicLabel = fulfillmentShortLabel(selectedFulfillment);

  const gicSubtext = selectedFulfillment === 'none' ? (
    <>
      <span>847 Maple Grove Dr</span>
      <span className="ld-wcp-responsive-header-desktop-gic-subtext-dot">&bull;</span>
      <span className="ld-wcp-responsive-header-desktop-gic-subtext-ellipsis">Sunnyvale Supercenter</span>
    </>
  ) : selectedFulfillment === 'pickup' ? (
    <span className="ld-wcp-responsive-header-desktop-gic-subtext-ellipsis">Carrollton Supercenter</span>
  ) : (
    <span>3471 Park Ln</span>
  );

  const gicIconContent = (
    <GicTokenIcon
      token={fulfillmentGicToken(selectedFulfillment)}
      size={selectedFulfillment === 'none' ? 40 : 50}
      label={gicLabel}
    />
  );

  return (
    <>
      <header className="ld-wcp-responsive-header-desktop-view">
        <div className="ld-wcp-responsive-header-desktop-content">
          {/* Brand logo — resolves via --wcp-semantic-media-topNav-logo-compact,
              which themeManager swaps by changing data-ld-theme on <html>. */}
          <a
            href="#"
            className="ld-wcp-responsive-header-desktop-logo"
            aria-label="Homepage"
          >
            <span className="ld-wcp-responsive-header-desktop-logo-img" aria-hidden="true" />
          </a>
  
          {/* GIC: Location / Delivery selector */}
          <div className="ld-wcp-responsive-header-desktop-gic-wrap" ref={gicDropdownRef}>
            <div className={`ld-wcp-responsive-header-desktop-gic-section${gicOpen ? ' ld-wcp-responsive-header-desktop-gic-section-active' : ''}`}>
              <button
                type="button"
                className="ld-wcp-responsive-header-desktop-gic-button"
                onClick={() => openDropdown(gicOpen ? null : 'gic')}
              >
                <div className="ld-wcp-responsive-header-desktop-gic-icon">
                  {gicIconContent}
                </div>
                <div className="ld-wcp-responsive-header-desktop-gic-text">
                  <div className="ld-wcp-responsive-header-desktop-gic-label">{gicLabel}</div>
                  <div className="ld-wcp-responsive-header-desktop-gic-subtext">
                    {gicSubtext}
                  </div>
                </div>
                <div className={`ld-wcp-responsive-header-desktop-gic-chevron${gicOpen ? ' ld-wcp-responsive-header-desktop-gic-chevron-open' : ''}`}>
                  <Icon name="ChevronDown" className="ld-wcp-responsive-header-desktop-gic-chevron-icon" />
                </div>
              </button>
            </div>
  
            {/* Highlight Callout */}
            {showHighlight && !gicOpen && (
              <div
                role="status"
                aria-live="polite"
                className="ld-wcp-responsive-header-desktop-highlight"
              >
                <div className="ld-wcp-responsive-header-desktop-highlight-nubbin" />
                <div className="ld-wcp-responsive-header-desktop-highlight-icon">
                  <svg width="28" height="28" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                    <path d="M36 4.5C42.2657 4.5 48.2753 6.98864 52.7058 11.4192C57.1364 15.8497 59.625 21.8593 59.625 28.125C59.625 51.75 36 67.5 36 67.5C36 67.5 12.375 51.75 12.375 28.125C12.375 21.8593 14.8636 15.8497 19.2942 11.4192C23.7247 6.98864 29.7343 4.5 36 4.5ZM36 15.75C29.1655 15.75 23.625 21.2905 23.625 28.125C23.625 34.9595 29.1655 40.5 36 40.5C42.8345 40.5 48.375 34.9595 48.375 28.125C48.375 21.2905 42.8345 15.75 36 15.75Z" fill="#C7DBFF" />
                    <path d="M36 40.5C42.8345 40.5 48.375 34.9595 48.375 28.125C48.375 21.2905 42.8345 15.75 36 15.75C29.1655 15.75 23.625 21.2905 23.625 28.125C23.625 34.9595 29.1655 40.5 36 40.5Z" fill="#4DBDF5" />
                  </svg>
                </div>
                <div className="ld-wcp-responsive-header-desktop-highlight-text">
                  Is this the right location?
                </div>
                <button
                  onClick={() => setShowHighlight(false)}
                  className="ld-wcp-responsive-header-desktop-highlight-update-btn"
                >
                  Update
                </button>
                <button
                  type="button"
                  onClick={() => setShowHighlight(false)}
                  aria-label="Dismiss location prompt"
                  className="ld-wcp-responsive-header-desktop-highlight-close-btn"
                >
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                    <path d="M1 1L11 11M11 1L1 11" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                  </svg>
                </button>
              </div>
            )}
  
            {/* GIC Dropdown. The scrim itself renders as a sibling of <header>
                below, not nested here — see the comment there for why. */}
            {gicOpen && (
              <>
                <div className="ld-wcp-responsive-header-desktop-gic-dropdown">
                  {/* Fulfillment options section */}
                  <div className="ld-wcp-responsive-header-desktop-gic-options-section">
                    <div className="ld-wcp-responsive-header-desktop-gic-options-list">
                      {GIC_FULFILLMENT_OPTIONS.map((opt) => (
                        <button
                          key={opt.key}
                          type="button"
                          className="ld-wcp-responsive-header-desktop-gic-option-btn"
                          onClick={() => { const next = selectedFulfillment === opt.key ? 'none' : opt.key; emit('ui:header:fulfillment', {selection: next}); setSelectedFulfillment(next); }}
                        >
                          <div className="ld-wcp-responsive-header-desktop-gic-option-icon-wrap">
                            <GicTokenIcon token={opt.token} size={50} />
                            {selectedFulfillment === opt.key && (
                              <>
                                <svg
                                  className="ld-wcp-responsive-header-desktop-gic-selection-ring"
                                  viewBox="0 0 64 64"
                                  fill="none"
                                  xmlns="http://www.w3.org/2000/svg"
                                  aria-hidden="true"
                                >
                                  <circle cx="32" cy="32" r="30" stroke="currentColor" strokeWidth="4" />
                                </svg>
                                <button
                                  type="button"
                                  onClick={(e) => { e.stopPropagation(); setSelectedFulfillment('none'); }}
                                  className="ld-wcp-responsive-header-desktop-gic-deselect-btn"
                                  aria-label={`Deselect ${opt.label}`}
                                >
                                  <span className="ld-wcp-responsive-header-desktop-gic-deselect-badge">
                                    <svg className="ld-wcp-responsive-header-desktop-gic-deselect-circle" viewBox="0 0 21 21" fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                                      <circle cx="10.5" cy="10.5" r="10.5" />
                                    </svg>
                                    <span className="ld-wcp-responsive-header-desktop-gic-deselect-x" aria-hidden="true">
                                      <svg width="9" height="9" viewBox="0 0 9 9" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path fillRule="evenodd" clipRule="evenodd" d="M1.20967 0.157278C0.915456 -0.0714902 0.490033 -0.0506931 0.21967 0.21967C-0.0732233 0.512563 -0.0732233 0.987437 0.21967 1.28033L3.43934 4.5L0.21967 7.71967C-0.0732229 8.01256 -0.0732229 8.48744 0.21967 8.78033C0.490033 9.05069 0.915456 9.07149 1.20967 8.84272L1.28033 8.78033L4.5 5.56066L7.71967 8.78033L7.79033 8.84272C8.08454 9.07149 8.50997 9.05069 8.78033 8.78033C9.07322 8.48744 9.07322 8.01256 8.78033 7.71967L5.56066 4.5L8.78033 1.28033C9.07322 0.987437 9.07322 0.512563 8.78033 0.21967C8.50997 -0.0506931 8.08454 -0.0714902 7.79033 0.157278L7.71967 0.21967L4.5 3.43934L1.28033 0.21967L1.20967 0.157278Z" fill="currentColor" />
                                      </svg>
                                    </span>
                                  </span>
                                </button>
                              </>
                            )}
                          </div>
                          <span className="ld-wcp-responsive-header-desktop-gic-option-label">{opt.label}</span>
                        </button>
                      ))}
                    </div>
                  </div>
  
                  {/* Address & store cards */}
                  <div className="ld-wcp-responsive-header-desktop-gic-cards-section">
                    <div className="ld-wcp-responsive-header-desktop-gic-cards-list">
                      <button type="button" className="ld-wcp-responsive-header-desktop-gic-card">
                        <LocationSvg />
                        <span className="ld-wcp-responsive-header-desktop-gic-card-text-single">
                          1213 E Trinity Mills Rd, Dallas, TX 75220
                        </span>
                        <Icon name="ChevronRight" size="small" />
                      </button>
                      <button type="button" className="ld-wcp-responsive-header-desktop-gic-card">
                        <StoreSvg />
                        <div className="ld-wcp-responsive-header-desktop-gic-card-text-stack">
                          <span className="ld-wcp-responsive-header-desktop-gic-card-store-name">Carrollton Supercenter</span>
                          <span className="ld-wcp-responsive-header-desktop-gic-card-store-addr">1213 E Trinity Mills Rd, Dallas, TX 75220</span>
                        </div>
                        <Icon name="ChevronRight" size="small" />
                      </button>
                    </div>
                  </div>
                </div>
              </>
            )}
          </div>
  
          {/* Search Form */}
          <div
            ref={searchFormRef}
            className={`ld-wcp-responsive-header-desktop-search-form-wrap${searchOpen ? ' ld-wcp-responsive-header-desktop-search-form-wrap-focused' : ''}`}
          >
            <form
              className="ld-wcp-responsive-header-desktop-search-form"
              role="search"
              aria-label="Walmart Site-Wide"
              onSubmit={(e) => {
                e.preventDefault();
                handleSearchSubmit(searchQuery);
              }}
            >
              <div className={`ld-wcp-responsive-header-desktop-search-input-wrap${searchOpen ? ' ld-wcp-responsive-header-desktop-search-input-wrap-active' : ''}`}>
                <input
                  type="search"
                  name="q"
                  placeholder="Search everything at Walmart online and in store"
                  aria-label="Search"
                  role="combobox"
                  aria-expanded={searchOpen}
                  aria-controls="header-search-listbox"
                  aria-autocomplete="list"
                  autoComplete="off"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onFocus={() => {
                    openDropdown(null);
                    setSearchOpen(true);
                  }}
                  onClick={() => setSearchOpen(true)}
                  className="ld-wcp-responsive-header-desktop-search-input"
                />
                <div className="ld-wcp-responsive-header-desktop-search-actions">
                  {searchQuery.trim() && (
                    <IconButton
                      a11yLabel="Clear search"
                      size="medium"
                      UNSAFE_className="ld-wcp-responsive-header-desktop-search-clear-button"
                      onClick={() => {
                        setSearchQuery('');
                        setSearchOpen(true);
                      }}
                    >
                      <Icon name="Close" />
                    </IconButton>
                  )}
                  <IconButton
                    type="submit"
                    a11yLabel="Search"
                    size="medium"
                    UNSAFE_className="ld-wcp-responsive-header-desktop-search-button"
                    onClick={() => {
                      setSearchOpen(true);
                    }}
                  >
                    <Icon name="Search" />
                  </IconButton>
                </div>
              </div>
            </form>
            {searchOpen && (
              <>
                <div id="header-search-listbox" className="ld-wcp-responsive-header-desktop-search-results" role="listbox" aria-label="Search suggestions">
                  {searchQuery.trim() ? (
                    filteredSuggestions.length > 0 ? (
                      filteredSuggestions.map((suggestion, index) => {
                        const parts = highlightSuggestionParts(suggestion, searchQuery);
                        return (
                          <button
                            key={`${suggestion}-${index}`}
                            type="button"
                            role="option"
                            aria-selected={false}
                            className="ld-wcp-responsive-header-desktop-search-result-row"
                            onClick={() => {
                              setSearchQuery(suggestion);
                              handleSearchSubmit(suggestion);
                            }}
                          >
                            <span className="ld-wcp-responsive-header-desktop-search-result-text">
                              {parts.before && <span className="ld-wcp-responsive-header-desktop-search-result-strong">{parts.before}</span>}
                              <span>{parts.match || suggestion}</span>
                              {parts.after && <span className="ld-wcp-responsive-header-desktop-search-result-strong">{parts.after}</span>}
                            </span>
                            <span className="ld-wcp-responsive-header-desktop-search-result-icon">
                              <ArrowUpLeftSvg />
                            </span>
                          </button>
                        );
                      })
                    ) : (
                      <div className="ld-wcp-responsive-header-desktop-search-empty-state">
                        No matching suggestions found.
                      </div>
                    )
                  ) : (
                    <>
                      <section className="ld-wcp-responsive-header-desktop-typeahead-section">
                        <h3 className="ld-wcp-responsive-header-desktop-typeahead-section-heading">
                          Keep shopping for {KEEP_SHOPPING_CATEGORY}
                        </h3>
                        <TypeaheadHorizontalScrollSection>
                          {KEEP_SHOPPING_FOR.map((item) => (
                            <button
                              key={item.label}
                              type="button"
                              className="ld-wcp-responsive-header-desktop-typeahead-tile-button"
                              onClick={() => handleChipClick(item.label)}
                            >
                              {item.isFilter ? (
                                <div className="ld-wcp-responsive-header-desktop-typeahead-tile-filter">
                                  <span className="ld-wcp-responsive-header-desktop-typeahead-tile-filter-label">{item.label}</span>
                                </div>
                              ) : (
                                <div className="ld-wcp-responsive-header-desktop-typeahead-tile-image">
                                  <PlaceholderMedia
                                    shape="rect"
                                    label={item.label}
                                    width="100%"
                                    height="100%"
                                    className="ld-wcp-responsive-header-desktop-typeahead-tile-image-img"
                                  />
                                </div>
                              )}
                              <span className="ld-wcp-responsive-header-desktop-typeahead-tile-label">{item.label}</span>
                            </button>
                          ))}
                        </TypeaheadHorizontalScrollSection>
                      </section>
  
                      <TypeaheadSeparator />
  
                      <section className="ld-wcp-responsive-header-desktop-typeahead-section-padded">
                        <div className="ld-wcp-responsive-header-desktop-typeahead-section-heading-row">
                          <h3 className="ld-wcp-responsive-header-desktop-typeahead-section-heading" style={{ margin: 0 }}>
                            Grab your usuals
                          </h3>
                          <button type="button" className="ld-wcp-responsive-header-desktop-typeahead-my-items-link">
                            <span className="ld-wcp-responsive-header-desktop-typeahead-my-items-icon">
                              <HeartSvg />
                            </span>
                            <span className="ld-wcp-responsive-header-desktop-typeahead-my-items-label">My items</span>
                          </button>
                        </div>
                        <TypeaheadHorizontalScrollSection>
                          {GRAB_YOUR_USUALS.map((term) => (
                            <button
                              key={term}
                              type="button"
                              className="ld-wcp-responsive-header-desktop-typeahead-chip-button"
                              onClick={() => handleChipClick(term)}
                            >
                              <span className="ld-wcp-responsive-header-desktop-typeahead-chip-label">{term}</span>
                            </button>
                          ))}
                        </TypeaheadHorizontalScrollSection>
                      </section>
  
                      <TypeaheadSeparator />
  
                      {recentSearches.length > 0 && (
                        <>
                          <section className="ld-wcp-responsive-header-desktop-typeahead-section-padded">
                            <h3 className="ld-wcp-responsive-header-desktop-typeahead-section-heading">Your recent searches</h3>
                            <div>
                              {recentSearches.map((search, index) => (
                                <React.Fragment key={`${search}-${index}`}>
                                  <div className="ld-wcp-responsive-header-desktop-search-recent-row">
                                    <span className="ld-wcp-responsive-header-desktop-search-recent-icon">
                                      <HistorySvg />
                                    </span>
                                    <button
                                      type="button"
                                      className="ld-wcp-responsive-header-desktop-search-recent-term"
                                      onClick={() => handleRecentClick(search)}
                                    >
                                      {search}
                                    </button>
                                    <button
                                      type="button"
                                      className="ld-wcp-responsive-header-desktop-search-recent-remove"
                                      aria-label={`Remove ${search}`}
                                      onClick={() => handleRemoveRecent(index)}
                                    >
                                      <CloseSvg />
                                    </button>
                                  </div>
                                  {index < recentSearches.length - 1 && <TypeaheadSeparator />}
                                </React.Fragment>
                              ))}
                            </div>
                          </section>
                          <TypeaheadSeparator />
                        </>
                      )}
  
                      <section className="ld-wcp-responsive-header-desktop-typeahead-section-padded">
                        <h3 className="ld-wcp-responsive-header-desktop-typeahead-section-heading">Trending</h3>
                        <TypeaheadHorizontalScrollSection>
                          {TRENDING_SEARCHES.map((term) => (
                            <button
                              key={term}
                              type="button"
                              className="ld-wcp-responsive-header-desktop-typeahead-chip-button"
                              onClick={() => handleChipClick(term)}
                            >
                              <span className="ld-wcp-responsive-header-desktop-typeahead-chip-label">{term}</span>
                            </button>
                          ))}
                        </TypeaheadHorizontalScrollSection>
                      </section>
  
                      <TypeaheadSeparator />
  
                      <section className="ld-wcp-responsive-header-desktop-typeahead-section-padded">
                        <h3 className="ld-wcp-responsive-header-desktop-typeahead-section-heading">Your frequent searches</h3>
                        <TypeaheadHorizontalScrollSection>
                          {FREQUENT_SEARCHES.map((term) => (
                            <button
                              key={term}
                              type="button"
                              className="ld-wcp-responsive-header-desktop-typeahead-chip-button"
                              onClick={() => handleChipClick(term)}
                            >
                              <span className="ld-wcp-responsive-header-desktop-typeahead-chip-label">{term}</span>
                            </button>
                          ))}
                        </TypeaheadHorizontalScrollSection>
                      </section>
                    </>
                  )}
                </div>
              </>
            )}
          </div>
  
          {/* Navigation */}
          <nav aria-label={a11yNavLabel} className="ld-wcp-responsive-header-desktop-nav">
            <ul className="ld-wcp-responsive-header-desktop-nav-list">
              {/* Reorder / My Items */}
              <li>
                <div className="ld-wcp-responsive-header-desktop-dropdown-root" ref={reorderDropdownRef}>
                  <button
                    type="button"
                    className="ld-wcp-responsive-header-desktop-nav-button"
                    aria-haspopup="true"
                    aria-expanded={reorderOpen}
                    onClick={() => openDropdown(reorderOpen ? null : 'reorder')}
                  >
                    <HeartSvg />
                    <div className="ld-wcp-responsive-header-desktop-nav-content">
                      <div className="ld-wcp-responsive-header-desktop-nav-subtext">Reorder</div>
                      <div className="ld-wcp-responsive-header-desktop-nav-label">My Items</div>
                    </div>
                  </button>
  
                  {reorderOpen && (
                    <div className="ld-wcp-responsive-header-desktop-dropdown-panel ld-wcp-responsive-header-desktop-dropdown-panel-left" role="menu" aria-label="Reorder and My Items">
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <ReorderSvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Reorder</span>
                      </button>
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <ListsSvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Lists</span>
                      </button>
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <GiftSvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Registries</span>
                      </button>
                    </div>
                  )}
                </div>
              </li>
  
              {/* Account */}
              <li>
                <div className="ld-wcp-responsive-header-desktop-dropdown-root" ref={accountDropdownRef}>
                  <button
                    type="button"
                    className="ld-wcp-responsive-header-desktop-nav-button"
                    aria-haspopup="true"
                    aria-expanded={accountOpen}
                    onClick={() => openDropdown(accountOpen ? null : 'account')}
                  >
                    <UserSvg />
                    <div className="ld-wcp-responsive-header-desktop-nav-content">
                      <div className="ld-wcp-responsive-header-desktop-nav-subtext">Hi, Emilia</div>
                      <div className="ld-wcp-responsive-header-desktop-nav-label">Account</div>
                    </div>
                  </button>
  
                  {accountOpen && (
                    <div className="ld-wcp-responsive-header-desktop-dropdown-panel ld-wcp-responsive-header-desktop-dropdown-panel-right" role="menu" aria-label="Account navigation">
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <PurchaseHistorySvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Purchase History</span>
                      </button>
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <WalmartPlusLogoSvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Walmart+</span>
                      </button>
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <UserSvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Account</span>
                      </button>
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <SubscriptionSvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Subscriptions</span>
                      </button>
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <WalmartCashSvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Get Walmart Cash</span>
                      </button>
                      <div className="ld-wcp-responsive-header-desktop-dropdown-separator" role="separator" />
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <GlobeSvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Language | English</span>
                      </button>
                      <div className="ld-wcp-responsive-header-desktop-dropdown-separator" role="separator" />
                      <button type="button" role="menuitem" className="ld-wcp-responsive-header-desktop-dropdown-item" onClick={() => openDropdown(null)}>
                        <SignOutSvg />
                        <span className="ld-wcp-responsive-header-desktop-dropdown-item-label">Sign Out</span>
                      </button>
                    </div>
                  )}
                </div>
              </li>
  
              {/* Cart */}
              <li>
                <a href="#" className="ld-wcp-responsive-header-desktop-nav-button-cart" aria-label={`Cart contains ${cartCount} items`}>
                  <CartIcon count={cartCount} price={cartPrice} textColor="var(--ld-semantic-color-topNav-text-onFill, white)" />
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </header>

      {showDesktopSubNav && (
        <div className="ld-wcp-responsive-header-desktop-category-nav">
          <CategoryNav {...(a11yCategoryNavLabel ? {'aria-label': a11yCategoryNavLabel} : {})} />
        </div>
      )}

      {/* Scrims: true siblings of <header>, not descendants — a descendant
          with a z-index paints ABOVE its own ancestor's un-indexed content
          (confirmed: elementFromPoint over the logo returned the scrim div
          when it was nested inside the search form), which darkened the
          header itself even though the scrim's z-index was below the
          dropdown's/results'. As a sibling, each is simply behind the whole
          header (z-index 100). */}
      {gicOpen && (
        <div className="ld-wcp-responsive-header-desktop-scrim" onClick={() => openDropdown(null)} />
      )}
      {searchOpen && (
        <div className="ld-wcp-responsive-header-desktop-search-scrim" onClick={closeSearchResults} />
      )}
    </>
  );
}
ResponsiveHeaderDesktop.displayName = 'HeaderDesktop';


/* ========================================================================= */
/*                              MOBILE VIEW                                  */
/* ========================================================================= */


/**
 * MobileHeader - WCP pattern helper (demo only).
 *
 * Faithful visual replica of the Walmart mobile header.
 * Two-row layout: logo + cart on row 1, search bar on row 2.
 */

/* ---------- Inline CartIcon matching original ---------- */

function MobileCartIcon({ count = 0, price = '$0.00', textColor = 'white' }: { count?: number; price?: string; textColor?: string }) {
  return (
    <div className="ld-wcp-responsive-header-mobile-cart-icon-wrap">
      <div className="ld-wcp-responsive-header-mobile-cart-icon-relative">
        <Icon name="Cart" style={{ fontSize: 24, color: textColor }} />
        <div className="ld-wcp-responsive-header-mobile-cart-badge">
          {count > 99 ? '99+' : count}
        </div>
      </div>
      <div className="ld-wcp-responsive-header-mobile-cart-price" style={{ color: textColor }}>
        {price}
      </div>
    </div>
  );
}

/* ---------- Component ---------- */

interface ResponsiveHeaderMobileProps {
  cartCount?: number;
  cartPrice?: string;
  /** Accessible name for the mobile search form landmark. Override when multiple Headers share a page. */
  a11yMobileSearchLabel?: string;
}

function ResponsiveHeaderMobile({ cartCount: cartCountProp, cartPrice: cartPriceProp, a11yMobileSearchLabel = 'Walmart site-wide' }: ResponsiveHeaderMobileProps = {}) {
  const [searchQuery, setSearchQuery] = useState('');
  const { cartCount, cartPrice } = useHeaderCartSnapshot(cartCountProp, cartPriceProp);

  return (
    <header className="ld-wcp-responsive-header-mobile-view">
      {/* Row 1: Logo + Cart */}
      <div className="ld-wcp-responsive-header-mobile-row1">
        <a href="#" className="ld-wcp-responsive-header-mobile-logo-link" aria-label="Homepage">
          <span className="ld-wcp-responsive-header-mobile-logo-img" aria-hidden="true" />
        </a>
        <a
          href="#"
          className="ld-wcp-responsive-header-mobile-cart-link"
          aria-label={`Cart contains ${cartCount} items`}
        >
          <MobileCartIcon count={cartCount} price={cartPrice} textColor="var(--ld-semantic-color-text-inverse, white)" />
        </a>
      </div>

      {/* Row 2: Search bar (white pill, icon + input) matching source MobileHeader.module.css */}
      <form
        role="search"
        aria-label={a11yMobileSearchLabel}
        onSubmit={(e) => { e.preventDefault(); emit('ui:header:search-submit', {query: searchQuery}); }}
        className="ld-wcp-responsive-header-mobile-search-form"
      >
        <div className="ld-wcp-responsive-header-mobile-search-pill">
          <Icon name="Search" className="ld-wcp-responsive-header-mobile-search-icon" style={{ fontSize: 16 }} />
          <input
            type="search"
            placeholder="Search everything at Walmart online and in store"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            aria-label="Search Walmart"
            className="ld-wcp-responsive-header-mobile-search-input"
          />
          {searchQuery.trim() && (
            <button
              type="button"
              className="ld-wcp-responsive-header-mobile-search-clear"
              aria-label="Clear search"
              onClick={() => setSearchQuery('')}
            >
              <CloseSvg />
            </button>
          )}
        </div>
      </form>
    </header>
  );
}
ResponsiveHeaderMobile.displayName = 'HeaderMobile';


/* ========================================================================= */
/*                              MOBILE TOP NAV                               */
/* ========================================================================= */

/* ---------- Sub-nav chip data ---------- */

const subNavLinks = [
  'Departments',
  'Services',
  'Get it Fast',
  'Rollbacks & More',
  'Easter',
  'Pharmacy',
  'New Arrivals',
  'Dinner Made Easy',
  'Walmart+',
];

/* ---------- Inline CartIcon matching original ---------- */

function TopNavCartIcon({ count = 0, price = '$0.00' }: { count?: number; price?: string }) {
  return (
    <IconButton
      a11yLabel={`Cart contains ${count} items`}
      color="white"
      UNSAFE_className="ld-wcp-responsive-header-mobile-topnav-cart-wrap"
    >
      <div className="ld-wcp-responsive-header-mobile-topnav-cart-icon-wrap">
        <Icon name="Cart" style={{ fontSize: 24 }} />
        <div className="ld-wcp-responsive-header-mobile-topnav-cart-badge">
          {count}
        </div>
      </div>
      <div className="ld-wcp-responsive-header-mobile-topnav-cart-price">
        {price}
      </div>
    </IconButton>
  );
}

/* ---------- Shared GIC banner + panel ---------- */

/**
 * The pickup/delivery location picker that sits below the search row —
 * a collapsed banner ("How do you want your items? <address>") that expands
 * into the fulfillment options and location cards.
 *
 * Shared verbatim by the topnav mobile web variants AND both native
 * platforms: same options, same cards, same open/close behavior. It owns its
 * own open + selection state and its click-outside/Escape handling, so each
 * host just drops it in.
 */
function GicDeliveryBanner() {
  const [gicOpen, setGicOpen] = useState(false);
  const [selectedFulfillment, setSelectedFulfillment] = useState<FulfillmentOption>('none');
  const gicWrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!gicOpen) return;
    function handleMouseDown(e: MouseEvent) {
      if (gicWrapRef.current && !gicWrapRef.current.contains(e.target as Node)) {
        setGicOpen(false);
      }
    }
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') setGicOpen(false);
    }
    document.addEventListener('mousedown', handleMouseDown);
    document.addEventListener('keydown', handleKeyDown);
    return () => {
      document.removeEventListener('mousedown', handleMouseDown);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [gicOpen]);

  return (
    <div className="ld-wcp-responsive-header-mobile-topnav-delivery-wrap" ref={gicWrapRef}>
      <button
        type="button"
        className={cx(
          'ld-wcp-responsive-header-mobile-topnav-delivery-btn',
          gicOpen && 'ld-wcp-responsive-header-mobile-topnav-delivery-btn-open',
        )}
        aria-haspopup="true"
        aria-expanded={gicOpen}
        onClick={() => setGicOpen((open) => !open)}
      >
        <div className="ld-wcp-responsive-header-mobile-topnav-delivery-inner">
          {!gicOpen && (
            <GicTokenIcon
              token={fulfillmentGicToken(selectedFulfillment)}
              size={24}
              label={fulfillmentShortLabel(selectedFulfillment)}
            />
          )}
          <span className="ld-wcp-responsive-header-mobile-topnav-delivery-text">
            {gicOpen
              ? 'Pickup or delivery?'
              : selectedFulfillment === 'none'
                ? 'How do you want your items?'
                : fulfillmentShortLabel(selectedFulfillment)}
            {!gicOpen && (
              <span className="ld-wcp-responsive-header-mobile-topnav-delivery-address">{TOPNAV_GIC_ADDRESS}</span>
            )}
          </span>
        </div>
        <Icon
          name="ChevronDown"
          className={cx(
            'ld-wcp-responsive-header-mobile-topnav-chevron-icon',
            gicOpen && 'ld-wcp-responsive-header-mobile-topnav-chevron-icon-open',
          )}
          style={{ fontSize: 20 }}
        />
      </button>

      {gicOpen && (
        <div className="ld-wcp-responsive-header-mobile-topnav-gic-panel">
          <div className="ld-wcp-responsive-header-mobile-topnav-gic-options-list">
            {GIC_FULFILLMENT_OPTIONS.map((opt) => (
              <button
                key={opt.key}
                type="button"
                className="ld-wcp-responsive-header-mobile-topnav-gic-option-btn"
                aria-pressed={selectedFulfillment === opt.key}
                onClick={() => {
                  const next = selectedFulfillment === opt.key ? 'none' : opt.key;
                  emit('ui:header:fulfillment', {selection: next});
                  setSelectedFulfillment(next);
                }}
              >
                <GicTokenIcon token={opt.token} size={56} />
                <span className="ld-wcp-responsive-header-mobile-topnav-gic-option-label">{opt.label}</span>
              </button>
            ))}
          </div>

          <div className="ld-wcp-responsive-header-mobile-topnav-gic-cards-list">
            <div className="ld-wcp-responsive-header-mobile-topnav-gic-card-container">
              <button type="button" className="ld-wcp-responsive-header-mobile-topnav-gic-card-row">
                <LocationSvg />
                <span className="ld-wcp-responsive-header-mobile-topnav-gic-card-text">{TOPNAV_GIC_ADDRESS}</span>
                <Icon name="ChevronRight" size="small" />
              </button>
              <div className="ld-wcp-responsive-header-mobile-topnav-gic-card-separator" />
              <button type="button" className="ld-wcp-responsive-header-mobile-topnav-gic-card-row">
                <GlobeSvg />
                <span className="ld-wcp-responsive-header-mobile-topnav-gic-card-text">Ship to another country</span>
                <Icon name="ChevronRight" size="small" />
              </button>
            </div>

            {/* A single-row card (icon + text + chevron, no wrapping) reuses
                the desktop card class rather than combining
                `gic-card-container` (column) with `gic-card-row` (row) on
                one element — those two conflict on flex-direction, which
                stacked the icon/text/chevron vertically instead of a row. */}
            <button
              type="button"
              className="ld-wcp-responsive-header-desktop-gic-card"
            >
              <StoreSvg />
              <span className="ld-wcp-responsive-header-desktop-gic-card-text-stack">
                <span className="ld-wcp-responsive-header-desktop-gic-card-store-name">Katy Morton Ranch Rd Supercenter</span>
                <span className="ld-wcp-responsive-header-desktop-gic-card-store-addr">22850 MORTON RANCH RD, Katy, TX 77449</span>
              </span>
              <Icon name="ChevronRight" size="small" />
            </button>
          </div>

          <div className="ld-wcp-responsive-header-mobile-topnav-gic-handle" aria-hidden="true" />
        </div>
      )}
    </div>
  );
}
GicDeliveryBanner.displayName = 'HeaderGicDeliveryBanner';

/* ---------- Types ---------- */

export type ResponsiveHeaderMobileTopNavVariant = 'blue' | 'white';

interface ResponsiveHeaderMobileTopNavProps {
  variant?: ResponsiveHeaderMobileTopNavVariant;
  /** The GIC (pickup/delivery + location) banner below the search bar.
   *  On by default — like desktop's GIC section and the native GIC row, this
   *  is core header identity, not an opt-in extra. Set false only to hide it. */
  showDeliveryBanner?: boolean;
  cartCount?: number;
  cartPrice?: string;
  /** Accessible name for the topnav pill search form landmark. Override when multiple Headers share a page. */
  a11yMobileSearchLabel?: string;
}

/* ---------- Component ---------- */



function ResponsiveHeaderMobileTopNav({
  variant = 'blue',
  showDeliveryBanner = true,
  cartCount: cartCountProp,
  cartPrice: cartPriceProp,
  a11yMobileSearchLabel = 'Walmart search bar',
}: ResponsiveHeaderMobileTopNavProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const { cartCount, cartPrice } = useHeaderCartSnapshot(cartCountProp, cartPriceProp);

  const variantClass = variant === 'blue'
    ? 'ld-wcp-responsive-header-mobile-topnav-blue'
    : 'ld-wcp-responsive-header-mobile-topnav-white';

  return (
    <div className={cx('ld-wcp-responsive-header-mobile-view ld-wcp-responsive-header-mobile-topnav', variantClass)}>
      {/* Top bar */}
      <div className="ld-wcp-responsive-header-mobile-topnav-topbar">
        {/* Left: hamburger + logo */}
        <div className="ld-wcp-responsive-header-mobile-topnav-left">
          <IconButton
            a11yLabel="Menu"
            color="white"
            UNSAFE_className="ld-wcp-responsive-header-mobile-topnav-hamburger"
            onClick={() => {}}
          >
            <Icon name="Menu" className="ld-wcp-responsive-header-mobile-topnav-hamburger-icon" style={{ fontSize: 32 }} />
          </IconButton>
          <a href="#" aria-label="Homepage" className="ld-wcp-responsive-header-mobile-topnav-logo-link">
            <span className="ld-wcp-responsive-header-mobile-topnav-logo-img" aria-hidden="true" />
          </a>
        </div>

        {/* Center: search pill */}
        <form
          className="ld-wcp-responsive-header-mobile-topnav-search-pill"
          role="search"
          aria-label={`${a11yMobileSearchLabel} – navigation`}
          onSubmit={(e) => { e.preventDefault(); emit('ui:header:search-submit', {query: searchQuery}); }}
        >
          <input
            type="search"
            placeholder="Search Walmart"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            aria-label="Search Walmart"
            className="ld-wcp-responsive-header-mobile-topnav-search-input"
          />
          {searchQuery.trim() && (
            <button
              type="button"
              className="ld-wcp-responsive-header-mobile-topnav-search-clear"
              aria-label="Clear search"
              onClick={() => setSearchQuery('')}
            >
              <CloseSvg />
            </button>
          )}
          <button type="submit" className="ld-wcp-responsive-header-mobile-topnav-search-btn" aria-label="Search">
            <Icon name="Search" className="ld-wcp-responsive-header-mobile-topnav-search-icon" style={{ fontSize: 14 }} />
          </button>
        </form>

        {/* Right: cart */}
        <TopNavCartIcon count={cartCount} price={cartPrice} />
      </div>

      {/* Delivery banner */}
      {showDeliveryBanner && <GicDeliveryBanner />}

    </div>
  );
}
ResponsiveHeaderMobileTopNav.displayName = 'HeaderMobileTopNav';


/* ========================================================================= */
/*                              NATIVE APP VIEW                              */
/* ========================================================================= */

/**
 * ResponsiveHeaderNative - WCP pattern helper (demo only).
 *
 * Faithful visual replica of the Walmart native app top bar. Android and iOS
 * share the same search bar and GIC (pickup/delivery + address) row — the
 * only difference is the identity row: Android folds search and cart into
 * one row with no separate logo, matching Android's search-in-the-toolbar
 * convention, while iOS shows a centered logo with cart on the right above
 * its own search row, matching iOS's centered nav-bar title convention.
 */

type NativeHeaderPlatform = 'android' | 'ios';

interface ResponsiveHeaderNativeProps {
  platform: NativeHeaderPlatform;
  cartCount?: number;
  cartPrice?: string;
  /** Accessible name for the native search form landmark. Override when multiple Headers share a page. */
  a11yMobileSearchLabel?: string;
}

function ResponsiveHeaderNative({
  platform,
  cartCount: cartCountProp,
  cartPrice: cartPriceProp,
  a11yMobileSearchLabel = 'Walmart search bar',
}: ResponsiveHeaderNativeProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const { cartCount, cartPrice } = useHeaderCartSnapshot(cartCountProp, cartPriceProp);

  const cartLink = (
    <a href="#" className="ld-wcp-responsive-header-mobile-cart-link" aria-label={`Cart contains ${cartCount} items`}>
      <MobileCartIcon count={cartCount} price={cartPrice} textColor="var(--ld-semantic-color-text-inverse, white)" />
    </a>
  );

  const searchForm = (
    <form
      role="search"
      aria-label={a11yMobileSearchLabel}
      onSubmit={(e) => { e.preventDefault(); emit('ui:header:search-submit', {query: searchQuery}); }}
      className="ld-wcp-responsive-header-mobile-search-form"
    >
      <div className="ld-wcp-responsive-header-mobile-search-pill">
        <Icon name="Search" className="ld-wcp-responsive-header-mobile-search-icon" style={{ fontSize: 16 }} />
        <input
          type="search"
          placeholder="Search Walmart"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          aria-label="Search Walmart"
          className="ld-wcp-responsive-header-mobile-search-input"
        />
        {searchQuery.trim() && (
          <button
            type="button"
            className="ld-wcp-responsive-header-mobile-search-clear"
            aria-label="Clear search"
            onClick={() => setSearchQuery('')}
          >
            <CloseSvg />
          </button>
        )}
      </div>
    </form>
  );

  return (
    <div className={cx('ld-wcp-responsive-header-mobile-view', 'ld-wcp-responsive-header-native', `ld-wcp-responsive-header-native-${platform}`)}>
      {platform === 'ios' ? (
        <>
          {/* Identity row: logo centered, cart on the right. Search gets its
              own row below rather than folding into this one, like Android does. */}
          <div className="ld-wcp-responsive-header-native-ios-row">
            <span aria-hidden="true" />
            <a href="#" aria-label="Homepage" className="ld-wcp-responsive-header-native-ios-logo-link">
              <span className="ld-wcp-responsive-header-native-ios-logo-img" aria-hidden="true" />
            </a>
            {cartLink}
          </div>
          {searchForm}
        </>
      ) : (
        // Android: search and cart share one row — no separate logo row.
        <div className="ld-wcp-responsive-header-native-search-row">
          {searchForm}
          {cartLink}
        </div>
      )}

      {/* GIC row — the same component the topnav mobile web variants use, so
          native and mobile web stay identical by construction. */}
      <GicDeliveryBanner />
    </div>
  );
}
ResponsiveHeaderNative.displayName = 'HeaderNative';


/* ========================================================================= */
/*                              WRAPPER COMPONENT                            */
/* ========================================================================= */

export type MobileHeaderVariant = 'classic' | 'topnav-blue' | 'topnav-white' | 'native-android' | 'native-ios';

export interface HeaderProps {
  cartCount?: number;
  cartPrice?: string;
  mobileVariant?: MobileHeaderVariant;
  /** The category/department nav strip under the desktop top bar. On by default. */
  showDesktopSubNav?: boolean;
  showMobileSubNav?: boolean;
  /** The GIC (pickup/delivery + location) banner on the topnav mobile web
   *  variants. On by default, matching desktop's GIC section and native's
   *  GIC row — set false only to hide it. No effect on `classic` or the
   *  native variants, which have their own always-on location picker. */
  showMobileDeliveryBanner?: boolean;
  /**
   * Override the desktop nav landmark label ("Account and Cart").
   * Pass a unique value when rendering multiple Headers on the same page
   * so each navigation landmark is distinguishable by assistive technology.
   */
  a11yNavLabel?: string;
  /**
   * Override the mobile search form landmark label.
   * Pass a unique value when rendering multiple Headers on the same page.
   * Classic default: "Walmart site-wide". Avoid including the word "search" — the role conveys that. Pass a unique value when rendering multiple Headers on the same page.
   */
  a11yMobileSearchLabel?: string;
  /**
   * Override the category nav landmark label.
   * Pass a unique value when rendering multiple Headers on the same page.
   */
  a11yCategoryNavLabel?: string;
}

export function Header({
  cartCount,
  cartPrice,
  mobileVariant = 'classic',
  showDesktopSubNav = true,
  showMobileSubNav = true,
  showMobileDeliveryBanner = true,
  a11yNavLabel,
  a11yMobileSearchLabel,
  a11yCategoryNavLabel,
}: HeaderProps) {
  const commonProps = { cartCount, cartPrice, a11yNavLabel, a11yMobileSearchLabel };
  const isNative = mobileVariant === 'native-android' || mobileVariant === 'native-ios';
  const isTopNav = mobileVariant === 'topnav-blue' || mobileVariant === 'topnav-white';
  return (
    <div className="ld-wcp-responsive-header-root">
      <ResponsiveHeaderDesktop {...commonProps} showDesktopSubNav={showDesktopSubNav} a11yCategoryNavLabel={a11yCategoryNavLabel} />
      {mobileVariant === 'classic' ? (
        <ResponsiveHeaderMobile {...commonProps} />
      ) : isNative ? (
        <ResponsiveHeaderNative {...commonProps} platform={mobileVariant === 'native-android' ? 'android' : 'ios'} />
      ) : (
        <ResponsiveHeaderMobileTopNav
          {...commonProps}
          variant={mobileVariant === 'topnav-blue' ? 'blue' : 'white'}
          showDeliveryBanner={showMobileDeliveryBanner}
        />
      )}
      {showMobileSubNav && isTopNav && (
        <div className="ld-wcp-responsive-header-mobile-category-nav">
          <CategoryNav {...(a11yCategoryNavLabel ? {'aria-label': a11yCategoryNavLabel} : {})} />
        </div>
      )}
    </div>
  );
}
Header.displayName = 'Header';
