/* Auto-generated from Airtable "All Media" view — do not edit by hand */

import { AGENT_CUSTOMER_MEDIA_SVGS, AGENT_CUSTOMER_MEDIA_IMAGES, AGENT_CUSTOMER_MEDIA_TOKENS } from './customer';
import { AGENT_PARTNER_MEDIA_SVGS, AGENT_PARTNER_MEDIA_IMAGES, AGENT_PARTNER_MEDIA_TOKENS } from './partner';
import { AGENT_ASSOCIATE_MEDIA_SVGS, AGENT_ASSOCIATE_MEDIA_IMAGES, AGENT_ASSOCIATE_MEDIA_TOKENS } from './associate';
import { AGENT_DEVELOPER_MEDIA_SVGS, AGENT_DEVELOPER_MEDIA_IMAGES, AGENT_DEVELOPER_MEDIA_TOKENS } from './developer';
import { AGENT_WIBEY_MEDIA_SVGS, AGENT_WIBEY_MEDIA_IMAGES, AGENT_WIBEY_MEDIA_TOKENS } from './wibey';
import { AGENT_WIBEY_LIGHT_MEDIA_SVGS, AGENT_WIBEY_LIGHT_MEDIA_IMAGES, AGENT_WIBEY_LIGHT_MEDIA_TOKENS } from './wibey-light';
import { AGENT_MY_WALMART_MEDIA_SVGS, AGENT_MY_WALMART_MEDIA_IMAGES, AGENT_MY_WALMART_MEDIA_TOKENS } from './my-walmart';
import { AGENT_ME_CAMPUS_MEDIA_SVGS, AGENT_ME_CAMPUS_MEDIA_IMAGES, AGENT_ME_CAMPUS_MEDIA_TOKENS } from './me-campus';
import { AGENT_WALLY_MEDIA_SVGS, AGENT_WALLY_MEDIA_IMAGES, AGENT_WALLY_MEDIA_TOKENS } from './wally';
import { WCP_MEDIA_SVGS, WCP_MEDIA_IMAGES, WCP_MEDIA_TOKENS } from './wcp';
import { WALMART_BUSINESS_MEDIA_SVGS, WALMART_BUSINESS_MEDIA_IMAGES, WALMART_BUSINESS_MEDIA_TOKENS } from './walmart-business';
import { WALMART_MX_MEDIA_SVGS, WALMART_MX_MEDIA_IMAGES, WALMART_MX_MEDIA_TOKENS } from './walmart-mx';
import { WALMART_CA_MEDIA_SVGS, WALMART_CA_MEDIA_IMAGES, WALMART_CA_MEDIA_TOKENS } from './walmart-ca';
import { WALMART_PLUS_MEDIA_SVGS, WALMART_PLUS_MEDIA_IMAGES, WALMART_PLUS_MEDIA_TOKENS } from './walmart-plus';
import { SAMS_CLUB_MEDIA_SVGS, SAMS_CLUB_MEDIA_IMAGES, SAMS_CLUB_MEDIA_TOKENS } from './sams-club';
import { SAMS_CLUB_MAVERICK_MEDIA_SVGS, SAMS_CLUB_MAVERICK_MEDIA_IMAGES, SAMS_CLUB_MAVERICK_MEDIA_TOKENS } from './sams-club-maverick';
import { MEMBERS_MARK_MEDIA_SVGS, MEMBERS_MARK_MEDIA_IMAGES, MEMBERS_MARK_MEDIA_TOKENS } from './members-mark';
import { BODEGA_MEDIA_SVGS, BODEGA_MEDIA_IMAGES, BODEGA_MEDIA_TOKENS } from './bodega';
import { WALMART_LEGACY_MEDIA_SVGS, WALMART_LEGACY_MEDIA_IMAGES, WALMART_LEGACY_MEDIA_TOKENS } from './walmart-legacy';

/** Media theme key → PascalCase name → inline SVG string. */
export const MEDIA_SVGS: Record<string, Record<string, string>> = {
  'customer': AGENT_CUSTOMER_MEDIA_SVGS,
  'partner': AGENT_PARTNER_MEDIA_SVGS,
  'associate': AGENT_ASSOCIATE_MEDIA_SVGS,
  'developer': AGENT_DEVELOPER_MEDIA_SVGS,
  'wibey': AGENT_WIBEY_MEDIA_SVGS,
  'wibey-light': AGENT_WIBEY_LIGHT_MEDIA_SVGS,
  'my-walmart': AGENT_MY_WALMART_MEDIA_SVGS,
  'me-campus': AGENT_ME_CAMPUS_MEDIA_SVGS,
  'wally': AGENT_WALLY_MEDIA_SVGS,
  'wcp': WCP_MEDIA_SVGS,
  'walmart-business': WALMART_BUSINESS_MEDIA_SVGS,
  'walmart-mx': WALMART_MX_MEDIA_SVGS,
  'walmart-ca': WALMART_CA_MEDIA_SVGS,
  'walmart-plus': WALMART_PLUS_MEDIA_SVGS,
  'sams-club': SAMS_CLUB_MEDIA_SVGS,
  'sams-club-maverick': SAMS_CLUB_MAVERICK_MEDIA_SVGS,
  'members-mark': MEMBERS_MARK_MEDIA_SVGS,
  'bodega': BODEGA_MEDIA_SVGS,
  'walmart-legacy': WALMART_LEGACY_MEDIA_SVGS,
};

/** Media theme key → PascalCase name → imported PNG asset URL. */
export const MEDIA_IMAGES: Record<string, Record<string, string>> = {
  'customer': AGENT_CUSTOMER_MEDIA_IMAGES,
  'partner': AGENT_PARTNER_MEDIA_IMAGES,
  'associate': AGENT_ASSOCIATE_MEDIA_IMAGES,
  'developer': AGENT_DEVELOPER_MEDIA_IMAGES,
  'wibey': AGENT_WIBEY_MEDIA_IMAGES,
  'wibey-light': AGENT_WIBEY_LIGHT_MEDIA_IMAGES,
  'my-walmart': AGENT_MY_WALMART_MEDIA_IMAGES,
  'me-campus': AGENT_ME_CAMPUS_MEDIA_IMAGES,
  'wally': AGENT_WALLY_MEDIA_IMAGES,
  'wcp': WCP_MEDIA_IMAGES,
  'walmart-business': WALMART_BUSINESS_MEDIA_IMAGES,
  'walmart-mx': WALMART_MX_MEDIA_IMAGES,
  'walmart-ca': WALMART_CA_MEDIA_IMAGES,
  'walmart-plus': WALMART_PLUS_MEDIA_IMAGES,
  'sams-club': SAMS_CLUB_MEDIA_IMAGES,
  'sams-club-maverick': SAMS_CLUB_MAVERICK_MEDIA_IMAGES,
  'members-mark': MEMBERS_MARK_MEDIA_IMAGES,
  'bodega': BODEGA_MEDIA_IMAGES,
  'walmart-legacy': WALMART_LEGACY_MEDIA_IMAGES,
};

/** Media theme key → PascalCase name → Airtable token name. */
export const MEDIA_TOKENS: Record<string, Record<string, string>> = {
  'customer': AGENT_CUSTOMER_MEDIA_TOKENS,
  'partner': AGENT_PARTNER_MEDIA_TOKENS,
  'associate': AGENT_ASSOCIATE_MEDIA_TOKENS,
  'developer': AGENT_DEVELOPER_MEDIA_TOKENS,
  'wibey': AGENT_WIBEY_MEDIA_TOKENS,
  'wibey-light': AGENT_WIBEY_LIGHT_MEDIA_TOKENS,
  'my-walmart': AGENT_MY_WALMART_MEDIA_TOKENS,
  'me-campus': AGENT_ME_CAMPUS_MEDIA_TOKENS,
  'wally': AGENT_WALLY_MEDIA_TOKENS,
  'wcp': WCP_MEDIA_TOKENS,
  'walmart-business': WALMART_BUSINESS_MEDIA_TOKENS,
  'walmart-mx': WALMART_MX_MEDIA_TOKENS,
  'walmart-ca': WALMART_CA_MEDIA_TOKENS,
  'walmart-plus': WALMART_PLUS_MEDIA_TOKENS,
  'sams-club': SAMS_CLUB_MEDIA_TOKENS,
  'sams-club-maverick': SAMS_CLUB_MAVERICK_MEDIA_TOKENS,
  'members-mark': MEMBERS_MARK_MEDIA_TOKENS,
  'bodega': BODEGA_MEDIA_TOKENS,
  'walmart-legacy': WALMART_LEGACY_MEDIA_TOKENS,
};

export { MEDIA_SVG_LOADERS, MEDIA_IMAGE_LOADERS } from './loaders';

export { AGENT_CUSTOMER_MEDIA_SVGS, AGENT_CUSTOMER_MEDIA_IMAGES, AGENT_CUSTOMER_MEDIA_TOKENS };
export { AGENT_PARTNER_MEDIA_SVGS, AGENT_PARTNER_MEDIA_IMAGES, AGENT_PARTNER_MEDIA_TOKENS };
export { AGENT_ASSOCIATE_MEDIA_SVGS, AGENT_ASSOCIATE_MEDIA_IMAGES, AGENT_ASSOCIATE_MEDIA_TOKENS };
export { AGENT_DEVELOPER_MEDIA_SVGS, AGENT_DEVELOPER_MEDIA_IMAGES, AGENT_DEVELOPER_MEDIA_TOKENS };
export { AGENT_WIBEY_MEDIA_SVGS, AGENT_WIBEY_MEDIA_IMAGES, AGENT_WIBEY_MEDIA_TOKENS };
export { AGENT_WIBEY_LIGHT_MEDIA_SVGS, AGENT_WIBEY_LIGHT_MEDIA_IMAGES, AGENT_WIBEY_LIGHT_MEDIA_TOKENS };
export { AGENT_MY_WALMART_MEDIA_SVGS, AGENT_MY_WALMART_MEDIA_IMAGES, AGENT_MY_WALMART_MEDIA_TOKENS };
export { AGENT_ME_CAMPUS_MEDIA_SVGS, AGENT_ME_CAMPUS_MEDIA_IMAGES, AGENT_ME_CAMPUS_MEDIA_TOKENS };
export { AGENT_WALLY_MEDIA_SVGS, AGENT_WALLY_MEDIA_IMAGES, AGENT_WALLY_MEDIA_TOKENS };
export { WCP_MEDIA_SVGS, WCP_MEDIA_IMAGES, WCP_MEDIA_TOKENS };
export { WALMART_BUSINESS_MEDIA_SVGS, WALMART_BUSINESS_MEDIA_IMAGES, WALMART_BUSINESS_MEDIA_TOKENS };
export { WALMART_MX_MEDIA_SVGS, WALMART_MX_MEDIA_IMAGES, WALMART_MX_MEDIA_TOKENS };
export { WALMART_CA_MEDIA_SVGS, WALMART_CA_MEDIA_IMAGES, WALMART_CA_MEDIA_TOKENS };
export { WALMART_PLUS_MEDIA_SVGS, WALMART_PLUS_MEDIA_IMAGES, WALMART_PLUS_MEDIA_TOKENS };
export { SAMS_CLUB_MEDIA_SVGS, SAMS_CLUB_MEDIA_IMAGES, SAMS_CLUB_MEDIA_TOKENS };
export { SAMS_CLUB_MAVERICK_MEDIA_SVGS, SAMS_CLUB_MAVERICK_MEDIA_IMAGES, SAMS_CLUB_MAVERICK_MEDIA_TOKENS };
export { MEMBERS_MARK_MEDIA_SVGS, MEMBERS_MARK_MEDIA_IMAGES, MEMBERS_MARK_MEDIA_TOKENS };
export { BODEGA_MEDIA_SVGS, BODEGA_MEDIA_IMAGES, BODEGA_MEDIA_TOKENS };
export { WALMART_LEGACY_MEDIA_SVGS, WALMART_LEGACY_MEDIA_IMAGES, WALMART_LEGACY_MEDIA_TOKENS };
